const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Json,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Rotate,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Arr.Exps.Front,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData
	];
};
self.C3_JsPropNameTable = [
	{Array_SpawnList: 0},
	{Array_Stack: 0},
	{Audio: 0},
	{JSON_Config: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{AJAX: 0},
	{stack_order: 0},
	{type: 0},
	{is_selected: 0},
	{is_moving: 0},
	{time_delay: 0},
	{active: 0},
	{dist_animation: 0},
	{is_animation: 0},
	{x_animation: 0},
	{y_animation: 0},
	{index_frame: 0},
	{row_prev: 0},
	{col_prev: 0},
	{time_delay_drop: 0},
	{is_drop: 0},
	{coin1: 0},
	{row: 0},
	{col: 0},
	{Stack: 0},
	{coin2: 0},
	{bg: 0},
	{board_bg: 0},
	{Tween: 0},
	{deals_btn: 0},
	{btn_merge_coin: 0},
	{barrr: 0},
	{coin3: 0},
	{coin4: 0},
	{coin5: 0},
	{coin6: 0},
	{coin7: 0},
	{coin8: 0},
	{coin9: 0},
	{coin10: 0},
	{coin11: 0},
	{coin12: 0},
	{coin13: 0},
	{coin14: 0},
	{coin15: 0},
	{coin16: 0},
	{coin17: 0},
	{coin18: 0},
	{coin19: 0},
	{coin20: 0},
	{slot_bg: 0},
	{is_unlock: 0},
	{price: 0},
	{stack_btn_unlock: 0},
	{coin: 0},
	{stack_btn_cost_txt: 0},
	{stack_border: 0},
	{box_decoration: 0},
	{label: 0},
	{ic_coin_booster: 0},
	{star_ic: 0},
	{btn_pause: 0},
	{score_best_txt: 0},
	{score_txt: 0},
	{coin_txt: 0},
	{types: 0},
	{pos: 0},
	{coin_pos: 0},
	{coin_level_txt: 0},
	{booster_ic: 0},
	{Rotate: 0},
	{fx_rotate_line: 0},
	{r: 0},
	{g: 0},
	{b: 0},
	{coin_level: 0},
	{Coin_item_line: 0},
	{Coin_item_line_color: 0},
	{is_bonus_after_scroll: 0},
	{bar_scroll: 0},
	{MoveTo: 0},
	{coin_bonus: 0},
	{coin_extra: 0},
	{booster_cost_txt: 0},
	{controller_bg: 0},
	{booster_btn: 0},
	{x_start: 0},
	{y_start: 0},
	{footer_container: 0},
	{footer_container_booster: 0},
	{Text: 0},
	{booster_btn_close: 0},
	{hammer: 0},
	{fx_smoke: 0},
	{home_title: 0},
	{home_decoration: 0},
	{btn_play_game: 0},
	{controller: 0},
	{popup_controller: 0},
	{title_controller: 0},
	{TYPE: 0},
	{audio_controller: 0},
	{sound: 0},
	{btn_continue: 0},
	{btn_home: 0},
	{box_decoration2: 0},
	{cup_ic: 0},
	{btn_replay: 0},
	{decoration_1: 0},
	{btn_play_agian: 0},
	{btn_restart: 0},
	{tryagain_btn_continue: 0},
	{hand: 0},
	{guide_step: 0},
	{guide: 0},
	{Text2: 0},
	{FamilyCoins: 0},
	{coin_isSpawn: 0},
	{coin_width: 0},
	{coin_height: 0},
	{coin_timeDelayDefault: 0},
	{coin_timeDelay: 0},
	{count: 0},
	{uid_stack: 0},
	{is_in_stack: 0},
	{ratio: 0},
	{nums_stack_spawn: 0},
	{index: 0},
	{nums_coin_spawn: 0},
	{type_start: 0},
	{ratio2: 0},
	{value: 0},
	{x_end: 0},
	{y_end: 0},
	{is_create: 0},
	{uid_coin: 0},
	{stack_typeSelected: 0},
	{stack_uidSelected: 0},
	{stack_isLoader: 0},
	{key: 0},
	{is_valid: 0},
	{is_all_match: 0},
	{time_delay_pop: 0},
	{uid: 0},
	{color: 0},
	{x_line: 0},
	{y_line: 0},
	{x_min: 0},
	{x_max: 0},
	{data: 0},
	{item: 0},
	{UI_stateLocked: 0},
	{Guide_step: 0},
	{booster_isActive: 0},
	{s: 0},
	{w: 0},
	{h: 0},
	{x: 0},
	{y: 0},
	{nums: 0},
	{is_ok: 0},
	{key_main: 0}
];

self.InstanceType = {
	Array_SpawnList: class extends self.IArrayInstance {},
	Array_Stack: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	coin1: class extends self.ISpriteInstance {},
	Stack: class extends self.ISpriteInstance {},
	coin2: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	board_bg: class extends self.ISpriteInstance {},
	deals_btn: class extends self.ISpriteInstance {},
	btn_merge_coin: class extends self.ISpriteInstance {},
	barrr: class extends self.ISpriteInstance {},
	coin3: class extends self.ISpriteInstance {},
	coin4: class extends self.ISpriteInstance {},
	coin5: class extends self.ISpriteInstance {},
	coin6: class extends self.ISpriteInstance {},
	coin7: class extends self.ISpriteInstance {},
	coin8: class extends self.ISpriteInstance {},
	coin9: class extends self.ISpriteInstance {},
	coin10: class extends self.ISpriteInstance {},
	coin11: class extends self.ISpriteInstance {},
	coin12: class extends self.ISpriteInstance {},
	coin13: class extends self.ISpriteInstance {},
	coin14: class extends self.ISpriteInstance {},
	coin15: class extends self.ISpriteInstance {},
	coin16: class extends self.ISpriteInstance {},
	coin17: class extends self.ISpriteInstance {},
	coin18: class extends self.ISpriteInstance {},
	coin19: class extends self.ISpriteInstance {},
	coin20: class extends self.ISpriteInstance {},
	slot_bg: class extends self.ISpriteInstance {},
	stack_btn_unlock: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	stack_btn_cost_txt: class extends self.ISpriteFontInstance {},
	stack_border: class extends self.ISpriteInstance {},
	box_decoration: class extends self.ISpriteInstance {},
	label: class extends self.ISpriteFontInstance {},
	ic_coin_booster: class extends self.ISpriteInstance {},
	star_ic: class extends self.ISpriteInstance {},
	btn_pause: class extends self.ISpriteInstance {},
	score_best_txt: class extends self.ISpriteFontInstance {},
	score_txt: class extends self.ISpriteFontInstance {},
	coin_txt: class extends self.ISpriteFontInstance {},
	coin_pos: class extends self.ISpriteInstance {},
	coin_level_txt: class extends self.ISpriteFontInstance {},
	booster_ic: class extends self.ISpriteInstance {},
	fx_rotate_line: class extends self.ISpriteInstance {},
	coin_level: class extends self.ISpriteInstance {},
	Coin_item_line: class extends self.ISpriteInstance {},
	Coin_item_line_color: class extends self.ISpriteInstance {},
	bar_scroll: class extends self.ISpriteInstance {},
	coin_bonus: class extends self.ISpriteInstance {},
	coin_extra: class extends self.ISpriteInstance {},
	booster_cost_txt: class extends self.ISpriteFontInstance {},
	controller_bg: class extends self.ISpriteInstance {},
	booster_btn: class extends self.ISpriteInstance {},
	footer_container: class extends self.ISpriteInstance {},
	footer_container_booster: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	booster_btn_close: class extends self.ISpriteInstance {},
	hammer: class extends self.ISpriteInstance {},
	fx_smoke: class extends self.ISpriteInstance {},
	home_title: class extends self.ISpriteInstance {},
	home_decoration: class extends self.ISpriteInstance {},
	btn_play_game: class extends self.ISpriteInstance {},
	popup_controller: class extends self.ISpriteInstance {},
	title_controller: class extends self.ISpriteFontInstance {},
	audio_controller: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	btn_continue: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	box_decoration2: class extends self.ISpriteInstance {},
	cup_ic: class extends self.ISpriteInstance {},
	btn_replay: class extends self.ISpriteInstance {},
	decoration_1: class extends self.ISpriteInstance {},
	btn_play_agian: class extends self.ISpriteInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	tryagain_btn_continue: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	guide: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	FamilyCoins: class extends self.ISpriteInstance {}
}