const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.Physics,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.imageloadingprogress,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgb,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Physics.Cnds.IsSleeping,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Acts.SetAwake,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Exps.X,
		C3.Plugins.Particles.Exps.Y,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Exps.projectversion,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Exps.Domain,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY
	];
};
self.C3_JsPropNameTable = [
	{Fade: 0},
	{Tween: 0},
	{intro_: 0},
	{Sine: 0},
	{txt_taptocontinue: 0},
	{Touch: 0},
	{debug: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{fade: 0},
	{txt_reset: 0},
	{Anchor: 0},
	{btn_main: 0},
	{btn_sound: 0},
	{btn_music: 0},
	{pause: 0},
	{btn_pause: 0},
	{bgPaused: 0},
	{b_play: 0},
	{txt_ver: 0},
	{warning: 0},
	{fontSizeDefault: 0},
	{txt_gameover: 0},
	{btn_restartGame: 0},
	{btn_restart: 0},
	{btn_fullscreen: 0},
	{btn_info: 0},
	{txt_infoBack: 0},
	{title: 0},
	{Browser: 0},
	{colorName: 0},
	{smallSize: 0},
	{music: 0},
	{Pin: 0},
	{txt_credits: 0},
	{txt_howTo: 0},
	{Rotate: 0},
	{part_sprite: 0},
	{part_sucess: 0},
	{txt_btnLevel: 0},
	{txt_paused: 0},
	{Flash: 0},
	{txt_gotit: 0},
	{Keyboard: 0},
	{tapOk: 0},
	{txt_tapToNext: 0},
	{txt_fsLock: 0},
	{p_end: 0},
	{Physics: 0},
	{objFloor: 0},
	{objBox: 0},
	{objTrophy: 0},
	{objGoal: 0},
	{objCircleStone: 0},
	{DragDrop: 0},
	{objTnt: 0},
	{barKeep: 0},
	{trophyArea: 0},
	{Timer: 0},
	{player: 0},
	{spell: 0},
	{tntArea: 0},
	{bgLevels: 0},
	{brightPlayer: 0},
	{explosion: 0},
	{p_pumpkin: 0},
	{picHowTo: 0},
	{curMove: 0},
	{handTuto: 0},
	{txt_label: 0},
	{lv: 0},
	{memPos: 0},
	{btn_level: 0},
	{winTrophy: 0},
	{wineff: 0},
	{txt_level: 0},
	{TopButtons: 0},
	{load_ok: 0},
	{storageName: 0},
	{progressLevel: 0},
	{spelling: 0},
	{curLevel: 0},
	{win: 0},
	{Sound: 0},
	{Music: 0},
	{fadeTime: 0},
	{in: 0},
	{levelsCount: 0}
];

self.InstanceType = {
	intro_: class extends self.ISpriteInstance {},
	txt_taptocontinue: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	debug: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	fade: class extends self.ITiledBackgroundInstance {},
	txt_reset: class extends self.ITextInstance {},
	btn_main: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	btn_pause: class extends self.ISpriteInstance {},
	bgPaused: class extends self.ITiledBackgroundInstance {},
	b_play: class extends self.ISpriteInstance {},
	txt_ver: class extends self.ITextInstance {},
	warning: class extends self.ITextInstance {},
	txt_gameover: class extends self.ITextInstance {},
	btn_restartGame: class extends self.ISpriteInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	btn_fullscreen: class extends self.ISpriteInstance {},
	btn_info: class extends self.ISpriteInstance {},
	txt_infoBack: class extends self.ITextInstance {},
	title: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	txt_credits: class extends self.ITextInstance {},
	txt_howTo: class extends self.ITextInstance {},
	part_sprite: class extends self.ISpriteInstance {},
	part_sucess: class extends self.IParticlesInstance {},
	txt_btnLevel: class extends self.ITextInstance {},
	txt_paused: class extends self.ITextInstance {},
	txt_gotit: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	txt_tapToNext: class extends self.ITextInstance {},
	txt_fsLock: class extends self.ITextInstance {},
	p_end: class extends self.IParticlesInstance {},
	objFloor: class extends self.ISpriteInstance {},
	objBox: class extends self.ISpriteInstance {},
	objTrophy: class extends self.ISpriteInstance {},
	objGoal: class extends self.ISpriteInstance {},
	objCircleStone: class extends self.ISpriteInstance {},
	objTnt: class extends self.ISpriteInstance {},
	barKeep: class extends self.ITiledBackgroundInstance {},
	trophyArea: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	spell: class extends self.ISpriteInstance {},
	tntArea: class extends self.ISpriteInstance {},
	bgLevels: class extends self.ISpriteInstance {},
	brightPlayer: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	p_pumpkin: class extends self.IParticlesInstance {},
	picHowTo: class extends self.ISpriteInstance {},
	handTuto: class extends self.ISpriteInstance {},
	txt_label: class extends self.ITextInstance {},
	btn_level: class extends self.ISpriteInstance {},
	winTrophy: class extends self.ISpriteInstance {},
	wineff: class extends self.ISpriteInstance {},
	txt_level: class extends self.ITextInstance {},
	TopButtons: class extends self.ISpriteInstance {}
}