const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.Spritefont2,
		C3.Plugins.Json,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Behaviors.MoveTo,
		C3.Plugins.Timeline,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Exps.ZIndex,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{row: 0},
	{col: 0},
	{active: 0},
	{value: 0},
	{cell: 0},
	{is_hint: 0},
	{is_hint_show: 0},
	{is_set: 0},
	{is_drag: 0},
	{uid_drag_object: 0},
	{type: 0},
	{num_cell_require: 0},
	{is_suggestion: 0},
	{cells: 0},
	{cells_hint: 0},
	{object1: 0},
	{border_pattern: 0},
	{width_object: 0},
	{height_object: 0},
	{object_drag1: 0},
	{object_drag2: 0},
	{object_drag3: 0},
	{object_drag4: 0},
	{object_drag5: 0},
	{object_drag6: 0},
	{object_drag7: 0},
	{object_drag8: 0},
	{object_drag9: 0},
	{object_drag10: 0},
	{object_drag11: 0},
	{object_drag12: 0},
	{is_checked: 0},
	{left: 0},
	{right: 0},
	{top: 0},
	{bottom: 0},
	{is_left: 0},
	{border_vertical: 0},
	{is_top: 0},
	{border_horizontal: 0},
	{cell_check: 0},
	{Tween: 0},
	{grid_align: 0},
	{pos: 0},
	{object_drag_cells: 0},
	{gird_12_objects: 0},
	{gird_10_objects: 0},
	{grid_align2: 0},
	{grid_align3: 0},
	{Touch: 0},
	{x_center: 0},
	{y_cennter: 0},
	{objects_check: 0},
	{object2: 0},
	{object3: 0},
	{object4: 0},
	{object5: 0},
	{object6: 0},
	{object7: 0},
	{object8: 0},
	{object9: 0},
	{object10: 0},
	{object11: 0},
	{object12: 0},
	{Array_Helper: 0},
	{pause_btn: 0},
	{box_decoration: 0},
	{btn_audio: 0},
	{ic_level: 0},
	{ic_coin: 0},
	{ic_hint: 0},
	{ic_coin2: 0},
	{level_txt: 0},
	{coin_txt: 0},
	{hint_cost_txt: 0},
	{home_title: 0},
	{home_btn_play: 0},
	{controller_bg: 0},
	{pause_controller: 0},
	{title_controller: 0},
	{pause_btn_play: 0},
	{pause_btn_home: 0},
	{pause_btn_restart: 0},
	{level_clear_controller: 0},
	{level_clear_btn_next: 0},
	{hint_btn: 0},
	{JSON_Config: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{AJAX: 0},
	{MoveTo: 0},
	{ic_coin_bonus: 0},
	{ic_coin_timeline: 0},
	{TimelineController: 0},
	{test: 0},
	{gird_14_objects: 0},
	{Text: 0},
	{FamilyBorder: 0},
	{FamilyDragObjects: 0},
	{Flash: 0},
	{FamilyObjects: 0},
	{FamilyGridDragObjects: 0},
	{x: 0},
	{y: 0},
	{x_min: 0},
	{y_min: 0},
	{x_max: 0},
	{y_max: 0},
	{uid: 0},
	{size: 0},
	{is_destroy_border: 0},
	{y_max_container: 0},
	{y_min_container: 0},
	{index: 0},
	{objects_go_back: 0},
	{angle_point: 0},
	{count: 0},
	{width: 0},
	{height: 0},
	{ang: 0},
	{nums_cell_require: 0},
	{is_complete: 0},
	{return_value: 0},
	{UI_stateLocked: 0},
	{coin_nums: 0},
	{w: 0},
	{h: 0},
	{s: 0},
	{key_main: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	cell: class extends self.ISpriteInstance {},
	object1: class extends self.ISpriteInstance {},
	border_pattern: class extends self.ITiledBackgroundInstance {},
	object_drag1: class extends self.ISpriteInstance {},
	object_drag2: class extends self.ISpriteInstance {},
	object_drag3: class extends self.ISpriteInstance {},
	object_drag4: class extends self.ISpriteInstance {},
	object_drag5: class extends self.ISpriteInstance {},
	object_drag6: class extends self.ISpriteInstance {},
	object_drag7: class extends self.ISpriteInstance {},
	object_drag8: class extends self.ISpriteInstance {},
	object_drag9: class extends self.ISpriteInstance {},
	object_drag10: class extends self.ISpriteInstance {},
	object_drag11: class extends self.ISpriteInstance {},
	object_drag12: class extends self.ISpriteInstance {},
	border_vertical: class extends self.ISpriteInstance {},
	border_horizontal: class extends self.ISpriteInstance {},
	cell_check: class extends self.ISpriteInstance {},
	grid_align: class extends self.ISpriteInstance {},
	object_drag_cells: class extends self.ISpriteInstance {},
	gird_12_objects: class extends self.ISpriteInstance {},
	gird_10_objects: class extends self.ISpriteInstance {},
	grid_align2: class extends self.ISpriteInstance {},
	grid_align3: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	objects_check: class extends self.ISpriteInstance {},
	object2: class extends self.ISpriteInstance {},
	object3: class extends self.ISpriteInstance {},
	object4: class extends self.ISpriteInstance {},
	object5: class extends self.ISpriteInstance {},
	object6: class extends self.ISpriteInstance {},
	object7: class extends self.ISpriteInstance {},
	object8: class extends self.ISpriteInstance {},
	object9: class extends self.ISpriteInstance {},
	object10: class extends self.ISpriteInstance {},
	object11: class extends self.ISpriteInstance {},
	object12: class extends self.ISpriteInstance {},
	Array_Helper: class extends self.IArrayInstance {},
	pause_btn: class extends self.ISpriteInstance {},
	box_decoration: class extends self.ISpriteInstance {},
	btn_audio: class extends self.ISpriteInstance {},
	ic_level: class extends self.ISpriteInstance {},
	ic_coin: class extends self.ISpriteInstance {},
	ic_hint: class extends self.ISpriteInstance {},
	ic_coin2: class extends self.ISpriteInstance {},
	level_txt: class extends self.ISpriteFontInstance {},
	coin_txt: class extends self.ISpriteFontInstance {},
	hint_cost_txt: class extends self.ISpriteFontInstance {},
	home_title: class extends self.ISpriteInstance {},
	home_btn_play: class extends self.ISpriteInstance {},
	controller_bg: class extends self.ISpriteInstance {},
	pause_controller: class extends self.ISpriteInstance {},
	title_controller: class extends self.ISpriteFontInstance {},
	pause_btn_play: class extends self.ISpriteInstance {},
	pause_btn_home: class extends self.ISpriteInstance {},
	pause_btn_restart: class extends self.ISpriteInstance {},
	level_clear_controller: class extends self.ISpriteInstance {},
	level_clear_btn_next: class extends self.ISpriteInstance {},
	hint_btn: class extends self.ISpriteInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	ic_coin_bonus: class extends self.ISpriteInstance {},
	ic_coin_timeline: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	test: class extends self.ITextInstance {},
	gird_14_objects: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	FamilyBorder: class extends self.ISpriteInstance {},
	FamilyDragObjects: class extends self.ISpriteInstance {},
	FamilyObjects: class extends self.ISpriteInstance {},
	FamilyGridDragObjects: class extends self.ISpriteInstance {}
}