const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetFontSize
	];
};
self.C3_JsPropNameTable = [
	{name: 0},
	{Tween: 0},
	{Text: 0},
	{Sine: 0},
	{Sine2: 0},
	{buttons: 0},
	{type: 0},
	{hLine: 0},
	{dir: 0},
	{player: 0},
	{Touch: 0},
	{border: 0},
	{Particles: 0},
	{playerShadow: 0},
	{lineShadow: 0},
	{TiledBackground: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{text_titles: 0},
	{player2: 0},
	{Anchor: 0},
	{bg: 0},
	{ффф: 0},
	{pageName: 0},
	{addLine: 0},
	{playerSpeed: 0},
	{playerShadowY: 0},
	{score: 0},
	{score_best: 0},
	{continue: 0},
	{combo: 0},
	{sound: 0}
];

self.InstanceType = {
	Text: class extends self.ITextInstance {},
	buttons: class extends self.ISpriteInstance {},
	hLine: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	border: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	playerShadow: class extends self.ISpriteInstance {},
	lineShadow: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	text_titles: class extends self.ITextInstance {},
	player2: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	ффф: class extends self.ISpriteInstance {}
}