var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var d=function(){};d.prototype=a;return new d};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},d={};try{return d.__proto__=a,d.a}catch(f){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,d){a.__proto__=d;if(a.__proto__!==d)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,d){a.prototype=$jscomp.objectCreate(d.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var f=$jscomp.setPrototypeOf;f(a,d)}else for(f in d)if("prototype"!=f)if(Object.defineProperties){var r=Object.getOwnPropertyDescriptor(d,f);r&&Object.defineProperty(a,f,r)}else a[f]=d[f];a.superClass_=d.prototype};var cur_level=1,pre_score=0,Game=function(){return Phaser.Scene.call(this,"game")||this};$jscomp.inherits(Game,Phaser.Scene);
Game.prototype.create=function(){function a(b,a){b=b.getBounds();a=a.getBounds();return Phaser.Geom.Intersects.RectangleToRectangle(b,a)}function d(){l="match";b.time.delayedCall(200,function(){play_sound("match",b);l="play";for(var a={},c=0;2>c;a={$jscomp$loop$prop$tile$7$9:a.$jscomp$loop$prop$tile$7$9},c++)a.$jscomp$loop$prop$tile$7$9=k[c],a.$jscomp$loop$prop$tile$7$9.tween.stop(),1===c&&(k=[]),b.tweens.add({targets:a.$jscomp$loop$prop$tile$7$9,scaleX:0,scaleY:0,duration:600,rotation:a.$jscomp$loop$prop$tile$7$9.rotation+
5,ease:"Back.easeIn",onComplete:function(a){return function(){for(var c=a.$jscomp$loop$prop$tile$7$9.uid,d=p.length,e=0;e<d;e++)if(p[e].uid===c){p.splice(e,1);break}a.$jscomp$loop$prop$tile$7$9.destroy(!0,!0);h++;v();0===p.length&&(w.remove(),l="end",1>n?b.time.delayedCall(1E3,A):b.time.delayedCall(1E3,r))}}(a)})})}function f(){if(0<n){if("play"===l||"bonus"===l)n--,B.width=Math.round(n/t*331),G.setText(n)}else if("play"===l){w.remove();play_sound("gameover",b);h>=bestscore&&localStorage.setItem("rf.find_pair",
bestscore);CA.submit_score(h);l="gameover";var a=b.add.rectangle(0,0,config.width,config.height,0).setOrigin(0);a.setInteractive();a.alpha=0;b.tweens.add({targets:a,alpha:.5,duration:200});b.add.sprite(360,670,"popup_gameover");b.add.sprite(360,425,"txt_gameover");draw_button(360,770,"restart",b);draw_button(360,890,"menu",b);b.add.text(config.width/2,610,"LEVEL "+(cur_level+1)+" FAILED!",{fontFamily:"vanilla",fontSize:35,align:"center",color:"#441F0B"}).setOrigin(.5);cur_level=0}}function r(){l=
"bonus";b.time.addEvent({delay:20,callback:function(){h++;v();f();0===n&&A()},repeat:n})}function C(a,c){b.tweens.add({targets:c,scaleX:a,scaleY:a,duration:100,ease:"Sine.easeOut"})}function A(){play_sound("completed",b);h>=bestscore&&localStorage.setItem("rf.find_pair",bestscore);CA.submit_score(h);pre_score="99x36"+String(h);l="completed";var a=b.add.rectangle(0,0,config.width,config.height,0).setOrigin(0);a.setInteractive();a.alpha=0;b.tweens.add({targets:a,alpha:.5,duration:200});b.add.sprite(360,
670,"popup_completed");b.add.sprite(360,425,"txt_completed");draw_button(360,770,"next",b);draw_button(360,890,"menu",b);b.add.text(460,549,h,{fontFamily:"vanilla",fontSize:35,align:"right",color:"#FFFFFF"}).setOrigin(1,.5);b.add.text(config.width/2,640,"LEVEL "+(cur_level+1),{fontFamily:"vanilla",fontSize:35,align:"center",color:"#441F0B"}).setOrigin(.5)}function v(){h>bestscore&&(bestscore=h,H.setText(bestscore));I.setText(h)}var x=this,b=this;this.add.sprite(config.width/2,config.height/2,"bg_game");
var l="play",D=!0,E=this.add.group(),q=23+(cur_level-1);30<q&&(q=30);var m=10+5*(cur_level-1),F=(config.width-580)/2,t=100-10*(cur_level-1);30>t&&(t=30);var n=t,w,h=0;if(pre_score){var e=String(pre_score);"99x36"===e.slice(0,5)&&(h=Number(e.replace("99x36","")))}pre_score=0;this.add.sprite(360,171,"header");this.add.sprite(197,161,"score_bar");this.add.sprite(514,167,"best_bar");this.add.sprite(375,247,"timer_bar");var B=this.add.tileSprite(210,247.2,331,27,"progress");B.setOrigin(0,.5);var G=this.add.text(375,
247,n,{fontFamily:"vanilla",fontSize:20,align:"center",color:"#FFFFFF"}).setOrigin(.5);this.add.sprite(193,242,"timer_icon");draw_button(659,57,"pause",this);e=draw_button(60,57,"sound_on",this);e.name="sound";check_audio(e);var I=this.add.text(300,161,h,{fontFamily:"vanilla",fontSize:33,align:"right",color:"#FFFFFF"}).setOrigin(1,.5),H=this.add.text(620,161,bestscore,{fontFamily:"vanilla",fontSize:33,align:"right",color:"#FFFFFF"}).setOrigin(1,.5);v();var p=[];e=[];for(var k=[],g=0;g<m;g++)e.push(Math.floor(Math.random()*
q));e=e.concat(e);e=e.sort(function(){return Math.random()-.5});q=e.length;for(m=0;m<q;m++)g=this.add.sprite(F+Math.round(580*Math.random()),400+Math.round(800*Math.random()),"tiles"),g.setInteractive(new Phaser.Geom.Circle(64,64,64),Phaser.Geom.Circle.Contains),g.setFrame(e[m]),g.tile=!0,g.uid=m,g.selected=!1,g.rotation=Math.PI/180*Math.round(360*Math.random()),p.push(g);e=0;a:for(;10>e;e++){m=!1;for(g=0;g<q;g++)for(var u=p[g],y=0;y<q;y++){var z=p[y];u.uid!=z.uid&&u.frame.name===z.frame.name&&a(u,
z)&&(m=!0,u.setPosition(F+Math.round(580*Math.random()),400+Math.round(800*Math.random())))}if(!m)break a}this.input.on("gameobjectdown",function(a,c){c.tile&&"play"===l&&!c.selected&&(play_sound("tile",b),D&&(D=!1,w=b.time.addEvent({delay:1E3,callback:f,loop:!0})),2>k.length&&(c.selected=!0,b.children.bringToTop(c),C(1.3,c),k.push(c),c.tween=b.tweens.add({targets:c,duration:4E3,rotation:c.rotation+Math.PI/180*360,loop:-1})),2===k.length&&(k[0].frame.name===k[1].frame.name?d():(C(1,k[0]),k[0].tween.stop(),
k[0].tween=null,k[0].selected=!1,k.shift())));c.button&&(play_sound("click",x),x.tweens.add({targets:c,scaleX:.9,scaleY:.9,yoyo:!0,ease:"Linear",duration:100,onComplete:function(){if("play"===l){if("pause"===c.name){l="paused";var a=b.add.rectangle(0,0,config.width,config.height,0).setOrigin(0);a.setInteractive();a.alpha=0;b.tweens.add({targets:a,alpha:.5,duration:200});var d=b.add.sprite(360,670,"popup_pause"),e=b.add.sprite(360,425,"txt_pause"),f=draw_button(360,620,"resume",b),g=draw_button(360,
736,"restart",b),h=draw_button(360,852,"menu",b),k=draw_button(610,370,"close",b);E.addMultiple([a,d,e,f,g,h,k])}}else if("resume"===c.name||"close"===c.name)l="play",E.clear(!0,!0);"sound"===c.name?switch_audio(c):"restart"===c.name?b.scene.restart():"menu"===c.name||"back"===c.name?b.scene.start("menu"):"next"===c.name&&(cur_level++,b.scene.restart())}},x))})};function play_sound(a,d){game_settings.sound&&d.sound.play(a)}
function switch_audio(a){game_settings[a.name]?(game_settings[a.name]=!1,a.setTexture("btn_sound_off")):(game_settings[a.name]=!0,a.setTexture("btn_sound_on"))}function check_audio(a){game_settings[a.name]?a.setTexture("btn_sound_on"):a.setTexture("btn_sound_off")}function draw_button(a,d,f,r){a=r.add.sprite(a,d,"btn_"+f).setInteractive();a.button=!0;a.name=f;return a}
var config={type:Phaser.AUTO,width:720,height:1280,scale:{mode:Phaser.Scale.FIT,parent:"game_content",autoCenter:Phaser.Scale.CENTER_BOTH},scene:[Boot,Load,Menu,Game]},game=new Phaser.Game(config);
