var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var h=function(){};h.prototype=a;return new h};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},h={};try{return h.__proto__=a,h.a}catch(k){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,h){a.__proto__=h;if(a.__proto__!==h)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,h){a.prototype=$jscomp.objectCreate(h.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var k=$jscomp.setPrototypeOf;k(a,h)}else for(k in h)if("prototype"!=k)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(h,k);f&&Object.defineProperty(a,k,f)}else a[k]=h[k];a.superClass_=h.prototype};var ad_timer1,ad_timer2,tmp_group,txt_points,state,cur_scope,Game=function(){return Phaser.Scene.call(this,"game")||this};$jscomp.inherits(Game,Phaser.Scene);
Game.prototype.create=function(){function a(c){txt_points.text=game_data.points;var b=n.getLength(),l=n.getChildren();if("char"==c){c={};for(var d=0;d<b;c={$jscomp$loop$prop$d$16:c.$jscomp$loop$prop$d$16},d++)if(l[d].empty){l[d].empty=!1;l[d].text=e.target_answer[d];e.current_answer.push(e.target_answer[d]);c.$jscomp$loop$prop$d$16=f.add.sprite(l[d].x,l[d].y,"hint_animation");c.$jscomp$loop$prop$d$16.play("hint");c.$jscomp$loop$prop$d$16.on("animationcomplete",function(b){return function(){b.$jscomp$loop$prop$d$16.destroy()}}(c));
break}}else if("all"==c)if(e.current_answer.length<e.target_answer.length){c={};for(d=0;d<b;c={$jscomp$loop$prop$d$3$18:c.$jscomp$loop$prop$d$3$18},d++)if(l[d].empty){l[d].empty=!1;l[d].text=e.target_answer[d];e.current_answer.push(e.target_answer[d]);c.$jscomp$loop$prop$d$3$18=f.add.sprite(l[d].x,l[d].y,"hint_animation");c.$jscomp$loop$prop$d$3$18.play("hint");c.$jscomp$loop$prop$d$3$18.on("animationcomplete",function(b){return function(){b.$jscomp$loop$prop$d$3$18.destroy()}}(c));break}setTimeout(function(){a("all")},
600)}else k()}function h(){e.current_answer=[];for(var c=n.getLength(),b=n.getChildren(),a=0;a<c;a++)b[a].empty||(b[a].empty=!0,b[a].text="");c=p.getLength();b=p.getChildren();for(a=0;a<c;a++)b[a].ready||(b[a].ready=!0,b[a].alpha=1)}function k(){game_data.cur_level++;game_data.new_level=!0;game_data.points+=2;var c=f.add.sprite(656,640,"check");c.setScale(0,0);f.tweens.add({targets:c,scaleX:1,scaleY:1,duration:400,ease:"Back.easeOut",onComplete:function(){play_sound("positive",f);f.tweens.add({targets:c,
scaleX:0,scaleY:0,delay:3E3,duration:300,ease:"Back.easeIn",onComplete:function(){game_data.cur_bg++;game_data.cur_bg>game_data.total_bg&&(game_data.cur_bg=1);next_level(f)}})}})}cur_scope=this;0<game_data.reward.a&&ad_timer(1,this);0<game_data.reward.b&&ad_timer(2,this);state="play";var f=this;tmp_group=null;tmp_group=this.add.group();this.add.image(480,640,"bg");this.add.image(480,448,"bg"+game_data.cur_bg);this.add.image(480,78,"header");this.add.image(480,1091,"footer");this.add.image(480,67,
"point_bar");draw_button(600,65,"plus",this);draw_button(192,71,"back",this);draw_button(770,71,"hint",this);var r=this.add.sprite(363,65,"star");game_data.new_level&&(game_data.new_level=!1,this.tweens.add({targets:r,scaleX:1.3,scaleY:1.3,yoyo:!0,ease:"Linear",duration:200}));txt_points=null;txt_points=this.add.text(478,67,game_data.points.toString(),{fontFamily:"robotomono",fontSize:"65px",align:"center",color:"#fff"});txt_points.setOrigin(.5,.5);var e={tile_size:75,target_answer:[],current_answer:[],
max_character:0},u=this.add.group(),n=this.add.group(),p=this.add.group(),v=this.add.group();draw_button(768,688,"clear",this);r=this.make.text({x:480,y:440,text:q[game_data.cur_level].q,origin:.5,style:{font:"bold 42px Arial",fill:"#fff",fontFamily:"robotomono",align:"center",wordWrap:{width:450}}});console.log(r.text.length);console.log("level "+game_data.cur_level);(function(){var c=q[game_data.cur_level].a.toUpperCase().split(""),b=c.length,a=-1,d=480-e.tile_size*b/2+e.tile_size/2,h=784;e.max_character=
c.length;for(var g=0;g<b;g++)" "==c[g]?(a=g,e.max_character--):e.target_answer.push(c[g]);-1!==a&&(h=752,d=480-e.tile_size*a/2+e.tile_size/2);for(c=0;c<b;c++)a!==c?(g=f.add.sprite(d+e.tile_size*c,h,"tile"),g.id=c,u.add(g),g=f.add.text(g.x,g.y,"",{fontFamily:"robotomono",fontSize:"45px",align:"center",color:"#489180"}),g.id=c,g.empty=!0,g.setOrigin(.5,.5),n.add(g)):(d=480-e.tile_size*(b+c)/2,h+=80)})();(function(){for(var a=0,b="qwertyuiopasdfghjklzxcvbnm".split(""),h=480-8*e.tile_size/2+e.tile_size/
2,d=992,k=e.target_answer,g=[],m=0;16>m;m++)m<k.length?g.push(k[m].toUpperCase()):g.push(b[Math.round(25*Math.random())].toUpperCase());for(b=g.length;b;)m=Math.floor(Math.random()*b--),k=g[b],g[b]=g[m],g[m]=k;for(b=0;16>b;b++)8==b&&(d+=93,a=0),k=f.add.sprite(h+e.tile_size*a,d,"tile_key").setInteractive(),k.id=g[b],k.name="keys",k.ready=!0,m=f.add.text(k.x,k.y,g[b],{fontFamily:"robotomono",fontSize:"50px",align:"center",color:"#C24F12"}),m.setOrigin(.5,.5),p.add(k),v.add(m),a++})();this.input.on("gameobjectdown",
function(c,b){if("keys"==b.name){if("play"==state&&(c=!0,e.current_answer.length==e.max_character&&(c=!1),b.ready&&c)){play_sound("key",f);b.ready=!1;b.alpha=.6;c=n.getLength();for(var l=n.getChildren(),d=0;d<c;d++)if(l[d].empty){l[d].empty=!1;l[d].text=b.id;e.current_answer.push(b.id);break}if(e.current_answer.length==e.max_character){b=!0;for(c=0;c<e.max_character;c++)if(e.current_answer[c]!==e.target_answer[c]){b=!1;break}b?k():play_sound("disappoint",f)}}}else if(b.button)if("clear"==b.name)this.tweens.add({targets:b,
scaleX:.9,scaleY:.9,yoyo:!0,duration:100,ease:"Linear",onComplete:function(){h()}});else if("back"==b.name&&"delay"!==state)play_sound("click",f),save_data(),this.scene.start("menu");else if("opt1"==b.name)0==b.frame.name&&(play_sound("hint",f),tmp_group.clear(!0,!0),state="play",game_data.points-=game_data.subs.a,a("char"));else if("opt2"==b.name)0==b.frame.name&&(play_sound("hint",f),tmp_group.clear(!0,!0),state="play",h(),game_data.points-=game_data.subs.b,a("all"));else if("hint"==b.name){if("play"==
state){play_sound("click",f);state="hint";b=this.add.sprite(480,592,"popup");c=this.add.text(480,264,"HINT",{fontFamily:"robotomono",fontSize:"52px",align:"center",color:"#fff"});c.setOrigin(.5,.5);l=this.add.sprite(752,264,"btn_close").setInteractive();l.name="close";l.button=!0;d=this.add.sprite(480,432,"btn_bar").setInteractive();d.name="opt1";d.button=!0;(game_data.points<game_data.subs.a||e.current_answer.length==e.target_answer.length)&&d.setFrame(1);var p=this.add.text(240,428,"Show one character",
{fontFamily:"robotomono",fontSize:"32px",align:"left",color:"#fff"});p.setOrigin(0,.5);var g=this.add.text(665,428,game_data.subs.a*(-1).toString(),{fontFamily:"robotomono",fontSize:"40px",align:"center",color:"#fff"});g.setOrigin(0,.5);var m=this.add.sprite(480,560,"btn_bar").setInteractive();m.name="opt2";m.button=!0;game_data.points<game_data.subs.b&&m.setFrame(1);var r=this.add.text(240,556,"Show answer",{fontFamily:"robotomono",fontSize:"32px",align:"left",color:"#fff"});r.setOrigin(0,.5);var t=
this.add.text(665,556,game_data.subs.b*(-1).toString(),{fontFamily:"robotomono",fontSize:"40px",align:"center",color:"#fff"});t.setOrigin(0,.5);tmp_group.add(b);tmp_group.add(l);tmp_group.add(d);tmp_group.add(m);tmp_group.add(p);tmp_group.add(r);tmp_group.add(g);tmp_group.add(t);tmp_group.add(c)}}else"close"==b.name&&"delay"!==state?this.tweens.add({targets:b,scaleX:.9,scaleY:.9,yoyo:!0,duration:100,ease:"Linear",onComplete:function(){tmp_group.clear(!0,!0);state="play"}}):"plus"==b.name?(play_sound("click",
f),this.tweens.add({targets:b,scaleX:.9,scaleY:.9,yoyo:!0,duration:100,ease:"Linear",onComplete:function(){if("play"==state){state="plus";var b=f.add.sprite(480,592,"popup"),a=f.add.text(480,264,"ADD POINT",{fontFamily:"robotomono",fontSize:"52px",align:"center",color:"#fff"});a.setOrigin(.5,.5);var c=draw_button(752,264,"close",f),d=draw_button(480,432,"bar",f);d.name="ad1";var e=f.add.text(240,428,"Show ad 1",{fontFamily:"robotomono",fontSize:"32px",align:"left",color:"#fff"});e.setOrigin(0,.5);
var h=f.add.text(665,428,"+"+game_data.get_reward.a.toString(),{fontFamily:"robotomono",fontSize:"40px",align:"center",color:"#fff"});h.setOrigin(0,.5);0<game_data.reward.a&&(d.setFrame(1),e.text="Wait "+game_data.reward.a+" seconds");var g=draw_button(480,560,"bar",f);g.name="ad2";var k=f.add.text(240,556,"Show ad 2",{fontFamily:"robotomono",fontSize:"32px",align:"left",color:"#fff"});k.setOrigin(0,.5);var l=f.add.text(665,556,"+"+game_data.get_reward.b.toString(),{fontFamily:"robotomono",fontSize:"40px",
align:"center",color:"#fff"});l.setOrigin(0,.5);0<game_data.reward.b&&(g.setFrame(1),k.text="Wait "+game_data.reward.b+" seconds");game_data.show_ad||(d.setFrame(1),g.setFrame(1));tmp_group.add(b);tmp_group.add(c);tmp_group.add(d);tmp_group.add(g);tmp_group.add(e);tmp_group.add(k);tmp_group.add(h);tmp_group.add(l);tmp_group.add(a)}}})):"ad1"==b.name&&"delay"!==state?0==b.frame.name&&(game_data.cur_ad_type=b.name,play_sound("hint",f),customAction("ad1")):"ad2"==b.name&&"delay"!==state&&0==b.frame.name&&
(game_data.cur_ad_type=b.name,play_sound("hint",f),customAction("ad2"))},this)};function next_level(a){q.length==game_data.cur_level?(1==confirm("Awesome! You're reached the last quiz.")?game_data.cur_level=1:game_data.cur_level--,save_data(),a.scene.start("menu")):a.scene.start("game")}function save_data(){localStorage.setItem(storage_key,JSON.stringify(game_data))}function play_sound(a,h){game_data.sound&&h.sound.play(a)}
function switch_audio(a){game_data[a.name]?(game_data[a.name]=!1,a.setTexture("btn_sound_off")):(game_data[a.name]=!0,a.setTexture("btn_sound_on"))}function check_audio(a){game_data[a.name]?a.setTexture("btn_sound_on"):a.setTexture("btn_sound_off")}function draw_button(a,h,k,f){a=f.add.sprite(a,h,"btn_"+k).setInteractive();a.button=!0;a.name=k;return a}
var config={type:Phaser.AUTO,width:960,height:1280,scale:{mode:Phaser.Scale.HEIGHT_CONTROLS_WIDTH,parent:"game_content",autoCenter:Phaser.Scale.CENTER_HORIZONTALLY},dom:{createContainer:!0},scene:[Boot,Load,Menu,Game]},game=new Phaser.Game(config);
