var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(b){var a=function(){};a.prototype=b;return new a};$jscomp.underscoreProtoCanBeSet=function(){var b={a:!0},a={};try{return a.__proto__=b,a.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(b,a){b.__proto__=a;if(b.__proto__!==a)throw new TypeError(b+" is not extensible");return b}:null;
$jscomp.inherits=function(b,a){b.prototype=$jscomp.objectCreate(a.prototype);b.prototype.constructor=b;if($jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(b,a)}else for(c in a)if("prototype"!=c)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(a,c);f&&Object.defineProperty(b,c,f)}else b[c]=a[c];b.superClass_=a.prototype};var Menu=function(){return Phaser.Scene.call(this,"menu")||this};$jscomp.inherits(Menu,Phaser.Scene);
Menu.prototype.create=function(){var b=this;cur_scope=this;var a=this;state="play";tmp_group=null;tmp_group=this.add.group();this.add.sprite(0,0,"bg_menu").setOrigin(0);var c=this.add.sprite(480,-200,"game_title");this.tweens.add({targets:c,y:320,duration:500,ease:"Back.easeOut"});draw_button(480,640,"play",this);draw_button(480,816,"free",this);c=draw_button(301,992,"sound",this);c.name="sound";game_data.sound||c.setFrame(1);draw_button(480,992,"rate",this);draw_button(660,992,"about",this);this.input.on("gameobjectdown",
function(c,d){d.button&&(play_sound("click",b),b.tweens.add({targets:d,scaleX:.9,scaleY:.9,yoyo:!0,ease:"Linear",duration:100,onComplete:function(){if("play"==d.name&&"play"==state)save_data(),a.scene.start("game");else if("free"==d.name&&"play"==state){if("play"==state){state="free";var b=a.add.sprite(480,592,"popup"),c=a.add.text(480,264,"FREE POINT",{fontFamily:"robotomono",fontSize:"52px",align:"center",color:"#fff"});c.setOrigin(.5,.5);var h=draw_button(752,264,"close",a),e=draw_button(480,432,
"bar",a);e.name="ad1";var k=a.add.text(240,428,"Show ad 1",{fontFamily:"robotomono",fontSize:"32px",align:"left",color:"#fff"});k.setOrigin(0,.5);var f=a.add.text(665,428,"+"+game_data.get_reward.a.toString(),{fontFamily:"robotomono",fontSize:"40px",align:"center",color:"#fff"});f.setOrigin(0,.5);0<game_data.reward.a&&(e.setFrame(1),k.text="Wait "+game_data.reward.a+" seconds");var g=draw_button(480,560,"bar",a);g.name="ad2";var l=a.add.text(240,556,"Show ad 2",{fontFamily:"robotomono",fontSize:"32px",
align:"left",color:"#fff"});l.setOrigin(0,.5);var m=a.add.text(665,556,"+"+game_data.get_reward.b.toString(),{fontFamily:"robotomono",fontSize:"40px",align:"center",color:"#fff"});m.setOrigin(0,.5);0<game_data.reward.b&&(g.setFrame(1),l.text="Wait "+game_data.reward.b+" seconds.");game_data.show_ad||(e.setFrame(1),g.setFrame(1));tmp_group.add(b);tmp_group.add(h);tmp_group.add(e);tmp_group.add(g);tmp_group.add(k);tmp_group.add(l);tmp_group.add(f);tmp_group.add(m);tmp_group.add(c)}}else"sound"==d.name&&
"play"==state?game_data.sound?(game_data.sound=!1,d.setFrame(1)):(game_data.sound=!0,d.setFrame(0)):"rate"==d.name&&"play"==state?customAction("rate"):"about"==d.name&&"play"==state?(state="about",b=a.add.sprite(480,592,"popup"),c=a.add.text(480,264,"ABOUT",{fontFamily:"robotomono",fontSize:"52px",align:"center",color:"#fff"}),c.setOrigin(.5,.5),h=draw_button(752,264,"close",a),e=a.make.text({x:480,y:620,text:'"Quiz Game"\nDeveloped by RedFoc\n\nMost game assets designed by Zuhria Alfitra\n\n\nhttps://redfoc.com\n(c) 2019',
origin:.5,style:{font:"40px robotomono",fill:"#7d382d",align:"center",strokeThickness:5,wordWrap:{width:500}}}),tmp_group.addMultiple([b,c,h,e])):"close"==d.name&&"delay"!==state?(state="play",tmp_group.clear(!0,!0)):"ad1"==d.name&&"delay"!==state?0==d.frame.name&&(game_data.cur_ad_type=d.name,play_sound("hint",a),customAction("ad1")):"ad2"==d.name&&"delay"!==state&&0==d.frame.name&&(game_data.cur_ad_type=d.name,play_sound("hint",a),customAction("ad2"))}},b))},this)};
