const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.TouchIndex,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.CompareFrame
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{PlayBtn__: 0},
	{speedTapTitle: 0},
	{Sine2: 0},
	{Tap: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{faq: 0},
	{Anchor: 0},
	{Timer_: 0},
	{isound: 0},
	{VolumeBox: 0},
	{txt_name: 0},
	{Tween: 0},
	{Text: 0},
	{player: 0},
	{Browser: 0},
	{cloud: 0},
	{star: 0},
	{star2: 0},
	{timer: 0},
	{startGame: 0},
	{eventData: 0},
	{score: 0},
	{play_rate: 0},
	{touch_name: 0},
	{sound: 0}
];

self.InstanceType = {
	PlayBtn__: class extends self.ISpriteInstance {},
	speedTapTitle: class extends self.ISpriteInstance {},
	Tap: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	faq: class extends self.ISpriteInstance {},
	Timer_: class extends self.ISpriteInstance {},
	isound: class extends self.ISpriteInstance {},
	VolumeBox: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	player: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	cloud: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	star2: class extends self.ISpriteInstance {}
}