var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(b){var e=function(){};e.prototype=b;return new e};$jscomp.underscoreProtoCanBeSet=function(){var b={a:!0},e={};try{return e.__proto__=b,e.a}catch(f){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(b,e){b.__proto__=e;if(b.__proto__!==e)throw new TypeError(b+" is not extensible");return b}:null;
$jscomp.inherits=function(b,e){b.prototype=$jscomp.objectCreate(e.prototype);b.prototype.constructor=b;if($jscomp.setPrototypeOf){var f=$jscomp.setPrototypeOf;f(b,e)}else for(f in e)if("prototype"!=f)if(Object.defineProperties){var h=Object.getOwnPropertyDescriptor(e,f);h&&Object.defineProperty(b,f,h)}else b[f]=e[f];b.superClass_=e.prototype};$jscomp.owns=function(b,e){return Object.prototype.hasOwnProperty.call(b,e)};
$jscomp.assign="function"==typeof Object.assign?Object.assign:function(b,e){for(var f=1;f<arguments.length;f++){var h=arguments[f];if(h)for(var l in h)$jscomp.owns(h,l)&&(b[l]=h[l])}return b};$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,f){b!=Array.prototype&&b!=Object.prototype&&(b[e]=f.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};
$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,e,f,h){if(e){f=$jscomp.global;b=b.split(".");for(h=0;h<b.length-1;h++){var l=b[h];l in f||(f[l]={});f=f[l]}b=b[b.length-1];h=f[b];e=e(h);e!=h&&null!=e&&$jscomp.defineProperty(f,b,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Object.assign",function(b){return b||$jscomp.assign},"es6","es3");var Game=function(){return Phaser.Scene.call(this,"game")||this};$jscomp.inherits(Game,Phaser.Scene);
Game.prototype.create=function(){function b(c,d){if(Math.round(10*Math.random()<x)&&0===k[d][c].type){var a=["a","b","c","d"],b=[1,1,2,2,3,4],e=Math.floor(Math.random()*b.length);if(8<=c+b[e])return!1;var f=Math.floor(4E3*Math.random());a=g.add.sprite(64+74*c,436+74*d,a[Math.floor(Math.random()*a.length)]+b[e]);a.setOrigin(0);a.setInteractive();a.type=b[e];a.pos={x:c,y:d};a.uid=f;g.input.setDraggable(a);r.push(a);for(a=c;a<c+b[e];a++)k[d][a].type="a"+b[e],k[d][a].uid=f}}function e(){play_sound("push",
g);m="push";for(var c=!1,d=0;8>d;d++)if(k[0][d].type){c=!0;break}if(c)return m="gameover",g.time.delayedCall(1E3,G),!1;for(c=1;10>c;c++)for(d=0;8>d;d++)k[c-1][d]=Object.assign({},k[c][d]),k[c][d]={type:0,uid:0};c=r.length;for(d=0;d<c;d++){var a=r[d];--a.pos.y;g.tweens.add({targets:a,y:436+74*a.pos.y,duration:200,ease:"Sine.easeOut"})}for(c=0;8>c;c++)b(c,9);c=r.length;for(d=0;d<c;d++)a=r[d],9===a.pos.y&&(a.y+=74,a.alpha=0,g.tweens.add({targets:a,y:436+74*a.pos.y,alpha:1,duration:200,ease:"Sine.easeOut"}));
g.time.delayedCall(250,function(){l(!0)?l():m="play"})}function f(c){for(var d=Object.assign({},k[c.pos.y][c.pos.x]),a=c.pos.x;a<c.pos.x+c.type;a++)k[c.pos.y][a]={type:0,uid:0};a=null;var b=c.pos.y+1;a:for(;10>b;b++){for(var e=c.pos.x;e<c.pos.x+c.type;e++)if(k[b][e].type)break a;a=b}for(b=c.pos.x;b<c.pos.x+c.type;b++)k[a][b]=Object.assign({},d);c.drop=a-c.pos.y;c.pos.y=a}function h(c){for(var d=[],a=0;9>a;a++)d.push(64+74*a-30);for(a=0;a<d.length-1;a++)if(c.x>=d[a]&&c.x<d[a+1]){u.x=64+74*a;break}}
function l(c,d){for(var a=r.length,b=0,h=8;0<=h;h--)for(var l=0;l<a;l++){var n=r[l];if(n.pos.y===h){for(var q=!0,p=n.pos.x;p<n.pos.x+n.type;p++)k[h+1][p].type&&(q=!1);if(q){if(c)return!0;b++;f(n)}}}if(c)return!1;b&&(m="drop");c={};for(h=0;h<a;c={$jscomp$loop$prop$tile$20$27:c.$jscomp$loop$prop$tile$20$27},h++)c.$jscomp$loop$prop$tile$20$27=r[h],c.$jscomp$loop$prop$tile$20$27.drop&&g.tweens.add({targets:c.$jscomp$loop$prop$tile$20$27,y:74*c.$jscomp$loop$prop$tile$20$27.pos.y+441,duration:200+50*c.$jscomp$loop$prop$tile$20$27.drop,
ease:"Sine.easeOut",onComplete:function(a){return function(){play_sound("drop",g);g.tweens.add({targets:a.$jscomp$loop$prop$tile$20$27,y:a.$jscomp$loop$prop$tile$20$27.y-10,duration:100,onComplete:function(){g.tweens.add({targets:a.$jscomp$loop$prop$tile$20$27,y:74*a.$jscomp$loop$prop$tile$20$27.pos.y+439,duration:100,onComplete:function(){g.tweens.add({targets:a.$jscomp$loop$prop$tile$20$27,y:436+74*a.$jscomp$loop$prop$tile$20$27.pos.y,duration:80,onComplete:function(){b--;if(0===b)if(A(!0))A();
else if(d)e();else{m="play";a:{for(var a=0,c=9;0<=c;c--){for(var g=!1,f=0;8>f;f++)k[c][f].type&&(g=!0);g&&a++;if(2<a)break a}e()}}}})}})}});a.$jscomp$loop$prop$tile$20$27.drop=!1}}(c)})}function H(c){for(var d=0;8>d;d++)k[c][d]={type:0,uid:0};for(d=r.length-1;0<=d;d--){var a=r[d];a.pos.y===c&&(a.destroy(!0,!0),r.splice(d,1))}}function A(c){for(var d=[],a=9;0<=a;a--){for(var b=!0,f=0;8>f;f++)if(!k[a][f].type){b=!1;break}if(b){if(c)return!0;d.push(a)}}if(c)return!1;if(d.length){play_sound("remove",
g);m="remove";c=8*d.length;1<d.length&&(c=Math.round(.7*c*d.length));p+=2*c;for(c=0;c<d.length;c++)I(d[c]);g.time.delayedCall(500,function(){l(!0)?l():(m="play",e());p>bestscore&&(bestscore=p,B.setText(bestscore));C.setText(p);400<p&&5===x&&(x=7)});var h=2;g.time.addEvent({delay:200,callback:function(){D.alpha=h%2?1:0;h++},repeat:8})}else m="play"}function I(c){var d=g.add.sprite(config.width/2-50,74*c+473,"blend");d.setBlendMode(Phaser.BlendModes.ADD);d.setOrigin(.7,.5);g.tweens.add({targets:d,scaleX:5,
duration:300,ease:"Sine.easeInOut",onComplete:function(){g.tweens.add({targets:d,scaleX:2,alpha:0,duration:100,onComplete:function(){d.destroy(!0,!0)}})}});var a=g.add.sprite(config.width/2+50,74*c+473,"blend");a.setBlendMode(Phaser.BlendModes.ADD);a.setOrigin(.3,.5);g.tweens.add({targets:a,scaleX:5,duration:300,ease:"Sine.easeInOut",onComplete:function(){H(c);g.tweens.add({targets:a,scaleX:2,alpha:0,duration:100,onComplete:function(){a.destroy(!0,!0)}})}})}function G(){play_sound("gameover",g);localStorage.setItem("rf.drop_it",
bestscore);var c=g.add.rectangle(0,0,config.width,config.height,0).setOrigin(0);c.setInteractive();c.alpha=.5;g.add.sprite(360,640,"popup_gameover");g.add.sprite(360,424,"txt_gameover");draw_button(360,805,"restart",g);draw_button(360,915,"menu",g);g.add.text(390,578,p,{fontFamily:"norwester",fontSize:35,align:"center",color:"#FFFFFF"}).setOrigin(.5);g.add.text(390,696,bestscore,{fontFamily:"norwester",fontSize:35,align:"center",color:"#FFFFFF"}).setOrigin(.5);CA.submit_score(p)}var y=this,g=this,
m="wait",z=!0,p=0,x=5;this.add.sprite(config.width/2,config.height/2,"background");this.add.sprite(config.width/2,0,"header").setOrigin(.5,0);this.add.sprite(config.width/2,720,"board");var D=this.add.sprite(360,271,"eye");D.alpha=0;var C=this.add.text(257,92,p,{fontFamily:"norwester",fontSize:32,align:"center",color:"#FFFFFF"});C.setOrigin(.5);var B=this.add.text(527,92,bestscore,{fontFamily:"norwester",fontSize:32,align:"center",color:"#FFFFFF"});B.setOrigin(.5);var n=draw_button(48,54,"sound_on",
this);n.name="sound";check_audio(n);draw_button(671,54,"pause",this);var E=this.add.group(),t=null,q=null,r=[],k=[],w,F,u=this.add.rectangle(64,436,74,740,16777215);u.setOrigin(0);u.alpha=.3;u.setVisible(!1);for(n=0;10>n;n++){k[n]=[];for(var v=0;8>v;v++)k[n][v]={type:0,uid:0}}for(n=7;10>n;n++)for(v=0;8>v;v++)b(v,n);this.time.delayedCall(500,function(){l(!0)?l():m="play"});this.input.on("gameobjectdown",function(c,d){d.button&&(play_sound("click",y),y.tweens.add({targets:d,scaleX:.9,scaleY:.9,yoyo:!0,
ease:"Linear",duration:100,onComplete:function(){if("play"===m){if("pause"===d.name){m="paused";var a=g.add.rectangle(0,0,config.width,config.height,0).setOrigin(0);a.setInteractive();a.alpha=.5;var c=g.add.sprite(360,670,"popup_pause"),b=g.add.sprite(360,423,"txt_pause"),e=draw_button(360,608,"resume",g),f=draw_button(360,720,"restart",g),h=draw_button(360,832,"menu",g);E.addMultiple([a,c,b,e,f,h])}}else"resume"===d.name&&(m="play",E.clear(!0,!0));"sound"===d.name?switch_audio(d):"restart"===d.name?
g.scene.restart():"menu"===d.name&&g.scene.start("menu")}},y))});this.input.on("dragstart",function(c,d,a,b){q=t=null;z=!1;if("play"===m||"drag"===m){play_sound("drag",g);m="drag";u.width=74*d.type;h(d);u.setVisible(!0);c=0;a=d.pos.x+d.type;if(8>a)for(;8>a;a++)if(k[d.pos.y][a].type){t=64+74*(a-d.type);break}else c++;if(0<d.pos.x)for(a=d.pos.x-1;0<=a;a--)if(k[d.pos.y][a].type){q=64+74*(a+1);break}else c++;c&&(z=!0);t||(t=656-74*d.type);q||(q=64)}});this.input.on("drag",function(c,b,a,e){"drag"===m&&
z&&(a>=q&&a<t?b.x=a:(a<q&&(b.x=q),a>=t&&(b.x=t)),h(b))});this.input.on("dragend",function(c,b,a,f){if(q){q=t=null;play_sound("dragend",g);c=[];for(a=0;9>a;a++)c.push(64+74*a-30);for(a=0;a<c.length-1;a++)if(b.x>=c[a]&&b.x<c[a+1]){w=b.pos.x;F=b.pos.y;b.pos.x=a;b.x=64+74*a;u.setVisible(!1);c=b;a=Object.assign({},k[F][w]);for(f=w;f<w+c.type;f++)k[c.pos.y][f]={type:0,uid:0};for(f=c.pos.x;f<c.pos.x+c.type;f++)k[c.pos.y][f]=Object.assign({},a);l(!0)?l(!1,!0):b.pos.x!=w&&e();break}}else"drag"===m&&(m="play")});
this.input.keyboard.on("keydown",function(b){})};function play_sound(b,e){game_data.sound&&e.sound.play(b)}function switch_audio(b){game_data[b.name]?(game_data[b.name]=!1,b.setTexture("btn_sound_off")):(game_data[b.name]=!0,b.setTexture("btn_sound_on"))}function check_audio(b){game_data[b.name]?b.setTexture("btn_sound_on"):b.setTexture("btn_sound_off")}function draw_button(b,e,f,h){b=h.add.sprite(b,e,"btn_"+f).setInteractive();b.button=!0;b.name=f;return b}
var config={type:Phaser.WEBGL,width:720,height:1280,scale:{mode:Phaser.Scale.FIT,parent:"game_content",autoCenter:Phaser.Scale.CENTER_BOTH},scene:[Boot,Load,Menu,Game]},game=new Phaser.Game(config);
