const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.TiledBg,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Behaviors.Anchor,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Timer,
		C3.Plugins.Tilemap,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.imageloadingprogress,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgb,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Exps.MaxSpeed,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Exps.X,
		C3.Plugins.Particles.Exps.Y,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Exps.MovingAngle,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.SetLayerVisible
	];
};
self.C3_JsPropNameTable = [
	{Fade: 0},
	{intro_: 0},
	{Sine: 0},
	{Flash: 0},
	{txt_taptocontinue: 0},
	{Touch: 0},
	{debug: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{fade: 0},
	{txt_reset: 0},
	{btn_main: 0},
	{btn_sound: 0},
	{btn_music: 0},
	{bgPaused: 0},
	{warning: 0},
	{btn_restart: 0},
	{b_play: 0},
	{txt_paused: 0},
	{tiledMain: 0},
	{btn_fullscreen: 0},
	{Browser: 0},
	{Tween: 0},
	{txt_howTo: 0},
	{txt_label: 0},
	{lv: 0},
	{selfPos: 0},
	{timeTween: 0},
	{btn_level: 0},
	{txt_btnLevel: 0},
	{colorName: 0},
	{smallSize: 0},
	{music: 0},
	{Pin: 0},
	{txt_credits: 0},
	{txt_infoBack: 0},
	{Anchor: 0},
	{btn_info: 0},
	{path: 0},
	{moves: 0},
	{MoveTo: 0},
	{truck: 0},
	{txt_waypoint: 0},
	{Timer: 0},
	{semaf: 0},
	{road: 0},
	{grass: 0},
	{fontSizeDefault: 0},
	{txt_gameover: 0},
	{tapOk: 0},
	{txt_tapToNext: 0},
	{txt_score: 0},
	{part_sucess: 0},
	{Rotate: 0},
	{part_sprite: 0},
	{p_end: 0},
	{truckUID: 0},
	{truckSign: 0},
	{Sine2: 0},
	{title: 0},
	{roadScenario: 0},
	{txt_level: 0},
	{Bullet: 0},
	{Wrap: 0},
	{cloud: 0},
	{hand: 0},
	{counter: 0},
	{initial: 0},
	{txt_counter: 0},
	{effect: 0},
	{TopButtons: 0},
	{load_ok: 0},
	{storageName: 0},
	{curLevel: 0},
	{progressLevel: 0},
	{userTouchBlocked: 0},
	{truckRegularSpeed: 0},
	{p_uid: 0},
	{increase: 0},
	{win: 0},
	{Sound: 0},
	{Music: 0},
	{fadeTime: 0},
	{in: 0},
	{levelsCount: 0}
];

self.InstanceType = {
	intro_: class extends self.ISpriteInstance {},
	txt_taptocontinue: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	debug: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	fade: class extends self.ITiledBackgroundInstance {},
	txt_reset: class extends self.ITextInstance {},
	btn_main: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	bgPaused: class extends self.ITiledBackgroundInstance {},
	warning: class extends self.ITextInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	b_play: class extends self.ISpriteInstance {},
	txt_paused: class extends self.ITextInstance {},
	tiledMain: class extends self.ITiledBackgroundInstance {},
	btn_fullscreen: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	txt_howTo: class extends self.ITextInstance {},
	txt_label: class extends self.ITextInstance {},
	btn_level: class extends self.ISpriteInstance {},
	txt_btnLevel: class extends self.ITextInstance {},
	txt_credits: class extends self.ITextInstance {},
	txt_infoBack: class extends self.ITextInstance {},
	btn_info: class extends self.ISpriteInstance {},
	truck: class extends self.ISpriteInstance {},
	txt_waypoint: class extends self.ITextInstance {},
	semaf: class extends self.ISpriteInstance {},
	road: class extends self.ITilemapInstance {},
	grass: class extends self.ITiledBackgroundInstance {},
	txt_gameover: class extends self.ITextInstance {},
	txt_tapToNext: class extends self.ITextInstance {},
	txt_score: class extends self.ITextInstance {},
	part_sucess: class extends self.IParticlesInstance {},
	part_sprite: class extends self.ISpriteInstance {},
	p_end: class extends self.IParticlesInstance {},
	truckSign: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	roadScenario: class extends self.ITilemapInstance {},
	txt_level: class extends self.ITextInstance {},
	cloud: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	txt_counter: class extends self.ITextInstance {},
	effect: class extends self.ISpriteInstance {},
	TopButtons: class extends self.ISpriteInstance {}
}