const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.advert,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Plugins.Particles,
		C3.Behaviors.Flash,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.advert.Acts.CreateInterstitial,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Spritefont2.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Particles.Acts.SetInitOpacity,
		C3.Plugins.Tilemap.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Tilemap.Exps.ColorValue,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetCharacterSpacing,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Tilemap.Acts.MoveAtAngle,
		C3.Plugins.Spritefont2.Acts.MoveAtAngle,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Tilemap.Cnds.CompareX,
		C3.Plugins.Tilemap.Acts.SetX,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.advert.Cnds.IsRewardedLoaded,
		C3.Plugins.advert.Acts.ShowRewarded,
		C3.Plugins.advert.Cnds.OnRewardedComplete,
		C3.Plugins.advert.Acts.CreateRewarded,
		C3.Plugins.advert.Cnds.OnRewardedFailedToLoad,
		C3.Plugins.advert.Cnds.OnRewardedCancelled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Tilemap.Exps.X,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.advert.Cnds.IsShowingInterstitial,
		C3.Plugins.advert.Cnds.IsShowingRewarded,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.advert.Cnds.OnInterstitialComplete,
		C3.Plugins.advert.Cnds.OnInterstitialCancelled,
		C3.Plugins.advert.Cnds.OnInterstitialFailedToLoad
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{MobileAdvert: 0},
	{Touch: 0},
	{Sine: 0},
	{Anchor: 0},
	{btn_home: 0},
	{btn_music: 0},
	{btn_start: 0},
	{pr_nx: 0},
	{r: 0},
	{Fade: 0},
	{bg_end: 0},
	{Sine2: 0},
	{bgg: 0},
	{fadeIN: 0},
	{fadeOUT: 0},
	{main_bg: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{type: 0},
	{Solid: 0},
	{Tilemap: 0},
	{Rotate: 0},
	{loader: 0},
	{point: 0},
	{Pin: 0},
	{checkpoint: 0},
	{finish: 0},
	{hand: 0},
	{rect: 0},
	{Platform: 0},
	{Sprite: 0},
	{transition: 0},
	{Particles: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{logo: 0},
	{check: 0},
	{Flash: 0},
	{player: 0},
	{box: 0},
	{box_2: 0},
	{box_3: 0},
	{text_finish: 0},
	{text_finish2: 0},
	{text_level: 0},
	{text_level2: 0},
	{level: 0},
	{text_mlevel: 0},
	{txt_ver: 0},
	{inf: 0},
	{STORAGENAME: 0},
	{checkpointX: 0},
	{checkpointY: 0},
	{revive: 0},
	{speedScenario: 0},
	{gameOver: 0},
	{currentLevel: 0},
	{currentLevel2: 0},
	{fin: 0},
	{control: 0},
	{load_ok: 0},
	{music: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	btn_home: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	btn_start: class extends self.ISpriteInstance {},
	pr_nx: class extends self.ISpriteInstance {},
	r: class extends self.ISpriteInstance {},
	bg_end: class extends self.ITiledBackgroundInstance {},
	bgg: class extends self.ISpriteInstance {},
	fadeIN: class extends self.ITiledBackgroundInstance {},
	fadeOUT: class extends self.ITiledBackgroundInstance {},
	main_bg: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	loader: class extends self.ISpriteInstance {},
	checkpoint: class extends self.ISpriteInstance {},
	finish: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	rect: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	transition: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	logo: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	box_2: class extends self.ISpriteInstance {},
	box_3: class extends self.ISpriteInstance {},
	text_finish: class extends self.ISpriteFontInstance {},
	text_finish2: class extends self.ISpriteFontInstance {},
	text_level: class extends self.ISpriteFontInstance {},
	text_level2: class extends self.ISpriteFontInstance {},
	text_mlevel: class extends self.ISpriteFontInstance {},
	txt_ver: class extends self.ISpriteFontInstance {},
	inf: class extends self.ISpriteInstance {}
}