var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(g){var l=function(){};l.prototype=g;return new l};$jscomp.underscoreProtoCanBeSet=function(){var g={a:!0},l={};try{return l.__proto__=g,l.a}catch(m){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(g,l){g.__proto__=l;if(g.__proto__!==l)throw new TypeError(g+" is not extensible");return g}:null;
$jscomp.inherits=function(g,l){g.prototype=$jscomp.objectCreate(l.prototype);g.prototype.constructor=g;if($jscomp.setPrototypeOf){var m=$jscomp.setPrototypeOf;m(g,l)}else for(m in l)if("prototype"!=m)if(Object.defineProperties){var u=Object.getOwnPropertyDescriptor(l,m);u&&Object.defineProperty(g,m,u)}else g[m]=l[m];g.superClass_=l.prototype};$jscomp.owns=function(g,l){return Object.prototype.hasOwnProperty.call(g,l)};
$jscomp.assign="function"==typeof Object.assign?Object.assign:function(g,l){for(var m=1;m<arguments.length;m++){var u=arguments[m];if(u)for(var y in u)$jscomp.owns(u,y)&&(g[y]=u[y])}return g};$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(g,l,m){g!=Array.prototype&&g!=Object.prototype&&(g[l]=m.value)};$jscomp.getGlobal=function(g){return"undefined"!=typeof window&&window===g?g:"undefined"!=typeof global&&null!=global?global:g};
$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(g,l,m,u){if(l){m=$jscomp.global;g=g.split(".");for(u=0;u<g.length-1;u++){var y=g[u];y in m||(m[y]={});m=m[y]}g=g[g.length-1];u=m[g];l=l(u);l!=u&&null!=l&&$jscomp.defineProperty(m,g,{configurable:!0,writable:!0,value:l})}};$jscomp.polyfill("Object.assign",function(g){return g||$jscomp.assign},"es6","es3");var Game=function(){return Phaser.Scene.call(this,"game")||this};$jscomp.inherits(Game,Phaser.Scene);
Game.prototype.create=function(){function g(a,f,d){var e=p.add.sprite(a,f,"obj"+d);p.tweens.add({targets:e,scaleY:0,scaleX:0,duration:150,ease:"Linear",onComplete:function(){e.destroy(!0,!0)}})}function l(a){for(var f=a.length,d,e;f;)e=Math.floor(Math.random()*f--),d=a[f],a[f]=a[e],a[e]=d;return a}function m(){r&&(r.clearTint(),r=null);for(var a=[],f=v.getLength(),d=v.getChildren(),e=0;10>e;e++)for(var c=0;8>c;c++)h[e][c].filled&&a.push(h[e][c].color);l(a);for(e=0;e<f;e++)c=d[e],c.color=a[e],c.setTexture("obj"+
c.color);P();y()?setTimeout(function(){play_sound("shuffle",p)},200):(console.log("not match"),m())}function u(){var a=v.getLength(),f=v.getChildren(),d=y();if(d){E=d;for(var e=0;e<a;e++){var c=f[e];(c.pos.x===d[0].x&&c.pos.y===d[0].y||c.pos.x===d[1].x&&c.pos.y===d[1].y)&&c.setTint(5233606)}}else alert("err");setTimeout(function(){play_sound("hint",p)},200)}function y(){for(var a=v.getLength(),f=v.getChildren(),d=0;d<a;d++){var e=f[d];a:{var c=e.pos;for(var b=h[c.y][c.x].color,g=0;10>g;g++)for(var k=
0;8>k;k++)if((g!==c.y||k!==c.x)&&h[g][k].filled&&h[g][k].color===b&&Q(c,{x:k,y:g})){c={x:k,y:g};break a}c=!1}if(c)return[e.pos,c]}return!1}function W(a){z="drop";for(var f=v.getLength(),d=v.getChildren(),e=0;e<f;e++){var c=d[e],b=h[c.pos.y][c.pos.x];if(0!=b.to.x||0!=b.to.y)c.pos.x+=b.to.x,c.pos.y+=b.to.y,p.tweens.add({targets:c,x:G+A.width*c.pos.x,y:H+A.height*c.pos.y,duration:200,ease:"Linear",onComplete:function(){a--;0===a&&(z="play",P(),y()||(0<player_data.shuffle_left?(C.setVisible(!0),play_sound("nomatch",
p)):(z="gameover1",setTimeout(R,1E3))))}})}}function P(){for(var a=0;10>a;a++)for(var f=0;8>f;f++)h[a][f].filled=!1,h[a][f].color=0,h[a][f].to=null;a=v.getLength();f=v.getChildren();for(var d=0;d<a;d++){var e=f[d];h[e.pos.y][e.pos.x].filled=!0;h[e.pos.y][e.pos.x].color=e.color}}function x(a){return Math.PI/180*a}function S(){for(var a=I.getChildren(),f=I.getLength(),d=0;d<f;d++)a[d].setVisible(!1)}function X(a){play_sound("connected",p);S();for(var f=I.getChildren(),d,e,c=0;c<a.length;c++){var b=
f[c];b.setVisible(!0);b.setPosition(G+A.width*a[c].x,H+A.height*a[c].y);0===c?e=a[c].x===a[c+1].x?a[c].y>a[c+1].y?"up":"down":a[c].x>a[c+1].x?"left":"right":c<a.length-1&&(a[c].x===a[c+1].x?a[c].y>a[c+1].y?(e="up","up"===d?b.setFrame(1):"down"!==d&&("left"===d?(b.setFrame(2),b.setRotation(x(180))):"right"===d&&(b.setFrame(2),b.setRotation(x(90))))):(e="down","up"!==d&&("down"===d?b.setFrame(1):"left"===d?(b.setFrame(2),b.setRotation(x(270))):"right"===d&&(b.setFrame(2),b.setRotation(x(0))))):a[c].x>
a[c+1].x?(e="left","up"===d?(b.setFrame(2),b.setRotation(x(0))):"down"===d?(b.setFrame(2),b.setRotation(x(90))):"left"===d&&b.setFrame(1)):(e="right","up"===d?(b.setFrame(2),b.setRotation(x(270))):"down"===d?(b.setFrame(2),b.setRotation(x(180))):"left"!==d&&"right"===d&&b.setFrame(1)));c===a.length-1&&(e=a[c].x===a[c-1].x?a[c].y>a[c-1].y?"up":"down":a[c].x>a[c-1].x?"left":"right",b.setFrame(0));0===b.frame.name?"up"===e?b.setRotation(x(270)):"down"===e?b.setRotation(x(90)):"left"===e?b.setRotation(x(180)):
"right"===e&&b.setRotation(x(0)):1===b.frame.name&&("up"===e||"down"===e?b.setRotation(x(90)):b.setRotation(x(0)));d=e}}function T(a,f){return 0<=a.x&&0<=a.y&&a.x<f[0].length&&a.y<f.length?!0:!1}function F(a,f,d,e,c){for(var b=[],g=1;10>g;g++){var k={x:f.x+a.x*g,y:f.y+a.y*g};if(T(k,e))if(e[k.y][k.x].filled){if(k.x===d.x&&k.y===d.y)return b.push(k),b;break}else if(b.push(k),c)if(1===a.x||-1===a.x){var h=F({x:0,y:-1},k,d,e);if(h){for(d=0;d<h.length;d++)b.push(h[d]);return b}if(k=F({x:0,y:1},k,d,e)){for(d=
0;d<k.length;d++)b.push(k[d]);return b}}else{if(h=F({x:-1,y:0},k,d,e)){for(d=0;d<h.length;d++)b.push(h[d]);return b}if(k=F({x:1,y:0},k,d,e)){for(d=0;d<k.length;d++)b.push(k[d]);return b}}else if(1===a.x||-1===a.x){if(J({x:0,y:1},k,d,e)){for(a=k.y+1;a<d.y+1;a++)b.push({x:k.x,y:a});return b}if(J({x:0,y:-1},k,d,e)){for(a=k.y-1;a>d.y-1;a--)b.push({x:k.x,y:a});return b}}else{if(J({x:1,y:0},k,d,e)){for(a=k.x+1;a<d.x+1;a++)b.push({x:a,y:k.y});return b}if(J({x:-1,y:0},k,d,e)){for(a=k.x-1;a>d.x-1;a--)b.push({x:a,
y:k.y});return b}}}return!1}function J(a,f,d,e){for(var c=1;10>c;c++){var b={x:f.x+a.x*c,y:f.y+a.y*c};if(T(b,e)){if(e[b.y][b.x].filled)return b.x===d.x&&b.y===d.y?!0:!1}else return!1}}function Q(a,f){for(var d=JSON.parse(JSON.stringify(h)),e=0;10>e;e++)d[e].unshift({filled:!1}),d[e].push({filled:!1});e=[];for(var c=0;10>c;c++)e.push({filled:!1});d.push(e);d.unshift(e);a.x++;a.y++;f.x++;f.y++;e=[];for(c=0;4>c;c++){var b={x:-1,y:0};1===c?b={x:1,y:0}:2===c?b={x:0,y:-1}:3===c&&(b={x:0,y:1});if(b=F(b,
a,f,d,!0)){var g=[];b.unshift(a);for(var k=0;k<b.length;k++)g.push({x:b[k].x-1,y:b[k].y-1});e.push(g)}}d=null;c=999;for(b=0;b<e.length;b++)e[b].length<c&&(c=e[b].length,d=e[b]);a.x--;a.y--;f.x--;f.y--;return d}function U(){Y.setText(player_data.shuffle_left);Z.setText(player_data.hint_left)}function R(){play_sound("gameover",p);player_data.score>best_score&&(best_score=player_data.score,localStorage.setItem("redfoc_onet_best",best_score));for(var a=v.getLength(),f=v.getChildren(),d=0;10>d;d++)for(var e=
0;8>e;e++)if(h[d][e].filled){var c=0;a:for(;c<a;c++){var b=f[c];if(b.pos.x===e&&b.pos.y===d){b.depth=0;break a}}}z="gameover";p.add.rectangle(0,0,config.width,config.height,0).setOrigin(0).alpha=.8;p.add.text(360,400,"GAMEOVER",{fontFamily:"PoetsenOne",fontSize:65,align:"center",color:"#FFFFFF"}).setOrigin(.5);p.add.text(360,480,"SCORE: "+player_data.score,{fontFamily:"PoetsenOne",fontSize:45,align:"center",color:"#FFFFFF"}).setOrigin(.5);draw_button(360,610,"restart",p);draw_button(360,700,"menu",
p);clear_data();localStorage.setItem("redfoc_onet_data",JSON.stringify(player_data))}function V(){var a={arr:h,data:player_data};last_array=JSON.parse(JSON.stringify(h));localStorage.setItem("redfoc_onet_array",JSON.stringify(a))}var M=this;this.add.sprite(0,0,"background").setOrigin(0);var z="play",n=0,p=this,E,N=!1,v=this.add.group();this.add.group();var I=this.add.group(),r=0,A={width:80,height:77},G=(config.width-8*A.width)/2+A.width/2,H=(config.height-10*A.height)/2+A.height/2,h=Array(10),t=
[],q=1,w=18+player_data.drop_mode;22<w&&(w=22);for(var B=0;40>B;B++)q>w&&(q=1),t.push(q),q++;t=t.concat(t);l(t);q=0;if(last_array)for(h=last_array,t=0;10>t;t++)for(q=0;8>q;q++)h[t][q].filled&&(w=h[t][q].color,B=this.add.sprite(G+A.width*q,H+A.height*t,"obj"+w).setInteractive(),B.color=w,B.piece=!0,B.pos={x:q,y:t},v.add(B));else for(w=0;10>w;w++){B=[];for(var K=0;8>K;K++){var O=t[q],aa={color:O,filled:!0},L=this.add.sprite(G+A.width*K,H+A.height*w,"obj"+O).setInteractive();L.color=O;L.piece=!0;L.pos=
{x:K,y:w};v.add(L);q++;B.push(aa)}h[w]=B}this.add.sprite(0,0,"header").setOrigin(0);this.add.sprite(config.width/2,35,"score_bar");var ba=this.add.text(config.width/2,35,String(player_data.score),{fontFamily:"robotomono",fontSize:40,align:"center",color:"#FFFFFF"}).setOrigin(.5);this.add.sprite(0,config.height,"footer").setOrigin(0,1);q=draw_button(650,40,"hint",this);0===player_data.hint_left&&(q.alpha=.5);t=draw_button(560,40,"shuffle",this);0===player_data.shuffle_left&&(t.alpha=.5);draw_button(70,
40,"home",this);w=draw_button(160,40,"sound_on",this);w.name="sound";check_audio(w);q=this.add.sprite(q.x+35,q.y+25,"circle");w=this.add.sprite(t.x+35,t.y+25,"circle");var Z=this.add.text(q.x,q.y,String(player_data.hint_left),{fontFamily:"robotomono",fontSize:30,align:"center",color:"#FFFFFF"}).setOrigin(.5),Y=this.add.text(w.x,w.y,String(player_data.shuffle_left),{fontFamily:"robotomono",fontSize:30,align:"center",color:"#FFFFFF"}).setOrigin(.5),D=this.add.sprite(180,180,"sign");D.setDepth(100);
D.setVisible(!1);var C=this.add.sprite(t.x,140,"arrow");C.setDepth(100);C.setVisible(!1);this.tweens.add({targets:D,scaleX:1.1,scaleY:1.1,ease:"Linear",duration:250,yoyo:!0,repeat:-1});this.tweens.add({targets:C,y:C.y+20,ease:"Linear",duration:250,yoyo:!0,repeat:-1});for(t=0;25>t;t++)q=this.add.sprite(80,80,"lines"),q.setDepth(100),q.setVisible(!1),I.add(q);this.input.keyboard.on("keydown",function(a,f){N=a.key});this.input.keyboard.on("keyup",function(a,f){N=!1});this.input.on("gameobjectdown",function(a,
f){if("z"===N)h[f.pos.y][f.pos.x].filled=!1,f.destroy(!0,!0);else if(f.button)play_sound("click",M),M.tweens.add({targets:f,scaleX:.9,scaleY:.9,yoyo:!0,ease:"Linear",duration:100,onComplete:function(){"play"===z&&("hint"===f.name?0<player_data.hint_left&&(player_data.hint_left--,U(),u(),0===player_data.hint_left&&(f.alpha=.5)):"shuffle"===f.name?0<player_data.shuffle_left&&(C.visible&&C.setVisible(!1),player_data.shuffle_left--,U(),m(),0===player_data.shuffle_left&&(f.alpha=.5)):"home"===f.name&&
p.scene.start("menu"));"sound"===f.name?switch_audio(f):"next"===f.name?p.scene.start("game"):"restart"===f.name?(player_data.drop_mode=0,player_data.score=0,p.scene.start("game")):"menu"===f.name&&p.scene.start("menu")}},M);else if(f.piece){if(E){a=v.getLength();for(var d=v.getChildren(),e=0;e<a;e++){var c=d[e];(c.pos.x===E[0].x&&c.pos.y===E[0].y||c.pos.x===E[1].x&&c.pos.y===E[1].y)&&c.clearTint()}E=null}r?"play"===z&&(play_sound("itemclick",p),f.pos.x!=r.pos.x||f.pos.y!=r.pos.y)&&(f.setTint(5233606),
h[f.pos.y][f.pos.x].color===h[r.pos.y][r.pos.x].color?(a=Q(r.pos,f.pos))?(player_data.score+=2,ba.setText(player_data.score),z="wait1",D.setVisible(!1),X(a),h[f.pos.y][f.pos.x].filled=!1,h[r.pos.y][r.pos.x].filled=!1,setTimeout(function(){z="wait";g(f.x,f.y,f.color);g(r.x,r.y,r.color);f.destroy(!0,!0);r.destroy(!0,!0);r=null;setTimeout(function(){if(1===player_data.drop_mode)var b="down";else if(2===player_data.drop_mode)b="up";else if(3===player_data.drop_mode)b="left";else if(4===player_data.drop_mode)b=
"right";else if(5===player_data.drop_mode)0===n?b="down":1===n&&(b="up"),n++,1<n&&(n=0);else if(6===player_data.drop_mode)0===n?b="left":1===n&&(b="right"),n++,1<n&&(n=0);else if(7===player_data.drop_mode)0===n?b="up":1===n&&(b="right"),n++,1<n&&(n=0);else if(8===player_data.drop_mode)0===n?b="down":1===n&&(b="left"),n++,1<n&&(n=0);else if(9===player_data.drop_mode)0===n?b="up":1===n?b="right":2===n?b="down":3===n&&(b="left"),n++,3<n&&(n=0);else if(9<player_data.drop_mode){var a=Math.floor(4*Math.random());
0===a?b="up":1===a?b="right":2===a?b="down":3===a&&(b="left")}a=b;b=0;if("down"===a)for(a=0;8>a;a++)for(var d=0,c=9;0<=c;c--)h[c][a].filled?(0!=d&&b++,h[c][a].to={x:0,y:d}):d++;else if("up"===a)for(a=0;8>a;a++)for(c=d=0;10>c;c++)h[c][a].filled?(0!=d&&b++,h[c][a].to={x:0,y:d}):d--;else if("left"===a)for(a=0;10>a;a++)for(c=d=0;8>c;c++)h[a][c].filled?(0!=d&&b++,h[a][c].to={x:d,y:0}):d--;else if("right"===a)for(a=0;10>a;a++)for(d=0,c=7;0<=c;c--)h[a][c].filled?(0!=d&&b++,h[a][c].to={x:d,y:0}):d++;if(b){a=
v.getLength();d=v.getChildren();for(var e=c=0;10>e;e++)for(var f=0;8>f;f++)if(h[e][f].filled){c++;var g=0;a:for(;g<a;g++){var l=d[g];if(l.pos.x===f&&l.pos.y===e){l.depth=c;break a}}}W(b)}else if(z="play",!y()){a:{for(b=0;10>b;b++)for(a=0;8>a;a++)if(h[b][a].filled){b=!1;break a}b=!0}b?(play_sound("completed",p),z="bonus",b="hint",1===Math.floor(2*Math.random())&&(b="shuffle"),"hint"===b?player_data.hint_left++:"shuffle"===b&&player_data.shuffle_left++,p.add.rectangle(0,0,config.width,config.height,
0).setOrigin(0).alpha=.8,p.add.text(360,320,"COMPLETED",{fontFamily:"PoetsenOne",fontSize:65,align:"center",color:"#FFFFFF"}).setOrigin(.5),p.add.sprite(360,480,b+"_icon"),p.add.text(360,600,"+1",{fontFamily:"PoetsenOne",fontSize:75,align:"center",color:"#FFFFFF"}).setOrigin(.5),draw_button(360,700,"next",p),last_array=null,player_data.drop_mode++,h=null,V()):0<player_data.shuffle_left?(C.setVisible(!0),play_sound("nomatch",p)):(z="gameover1",setTimeout(R,1E3))}V()},100);S()},300)):(r.clearTint(),
r=f,D.setPosition(f.x,f.y)):(r.clearTint(),r=f,D.setPosition(f.x,f.y))):"play"===z&&(play_sound("itemclick",p),r=f,f.setTint(5233606),D.setVisible(!0),D.setPosition(f.x,f.y))}},this);y()||last_array||this.scene.start("game")};function clear_data(){localStorage.removeItem("redfoc_onet_array");player_data=Object.assign({},def_player_data);last_array=null;localStorage.setItem("redfoc_onet_data",JSON.stringify(player_data))}function play_sound(g,l){game_data.sound&&l.sound.play(g)}
function switch_audio(g){game_data[g.name]?(game_data[g.name]=!1,g.setTexture("btn_sound_off")):(game_data[g.name]=!0,g.setTexture("btn_sound_on"))}function check_audio(g){game_data[g.name]?g.setTexture("btn_sound_on"):g.setTexture("btn_sound_off")}function draw_button(g,l,m,u){g=u.add.sprite(g,l,"btn_"+m).setInteractive();g.button=!0;g.name=m;return g}
var config={type:Phaser.AUTO,width:720,height:1080,scale:{mode:Phaser.Scale.FIT,parent:"game_content",autoCenter:Phaser.Scale.CENTER_BOTH},scene:[Boot,Load,Menu,Game]},game=new Phaser.Game(config);
