var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(b){var k=function(){};k.prototype=b;return new k};$jscomp.underscoreProtoCanBeSet=function(){var b={a:!0},k={};try{return k.__proto__=b,k.a}catch(l){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(b,k){b.__proto__=k;if(b.__proto__!==k)throw new TypeError(b+" is not extensible");return b}:null;
$jscomp.inherits=function(b,k){b.prototype=$jscomp.objectCreate(k.prototype);b.prototype.constructor=b;if($jscomp.setPrototypeOf){var l=$jscomp.setPrototypeOf;l(b,k)}else for(l in k)if("prototype"!=l)if(Object.defineProperties){var v=Object.getOwnPropertyDescriptor(k,l);v&&Object.defineProperty(b,l,v)}else b[l]=k[l];b.superClass_=k.prototype};var player_data={level:1,score:0},prev_target=0,Game=function(){return Phaser.Scene.call(this,"game")||this};$jscomp.inherits(Game,Phaser.Scene);
Game.prototype.create=function(){function b(a){m=JSON.parse(JSON.stringify(h));k(a,m[a.y][a.x]);if(2<=w){play_sound("match",e);a=[];for(var c=0;10>c;c++)for(var x=0;9>x;x++)if("checked"===m[c][x]){a.push({x:x,y:c});h[c][x]=-1;for(var f=x,d=c,b=g.length,l=0;l<b;l++){var y=g[l];if(y.pos.x===f&&y.pos.y===d){f=y.uid;d=g.length;for(b=0;b<d;b++)if(g[b].uid===f){g.splice(b,1);break}r.setPosition(y.x,y.y);r.explode();y.destroy(!0,!0);break}}}v(E("vertical"));for(c=a=0;c<w-1;c++)a+=10;F+=a;n+=a;G()}m=null;
if(2<=w)return w=0,!0;w=0;return!1}function k(a,c){w++;m[a.y][a.x]="checked";for(var e=[[-1,0],[1,0],[0,-1],[0,1]],f=0;4>f;f++){var d=a.x+e[f][0],b=a.y+e[f][1];0<=d&&9>d&&0<=b&&10>b&&"checked"!=m[b][d]&&m[b][d]===c&&k({x:d,y:b},c)}}function l(a,c){for(var b=g.length,e=0;e<b;e++){var d=g[e];if(d.pos.x===a&&d.pos.y===c)return d}}function v(a){a=void 0===a?"down":a;m=JSON.parse(JSON.stringify(h));var c=0,b=1;if("down"===a)for(a=0;9>a;a++)for(var f=0,d=9;0<=d;d--)m[d][a]=0,-1===h[d][a]?f++:f&&(m[d][a]=
f,c++);else if("up"===a)for(b=-1,a=0;9>a;a++)for(d=f=0;10>d;d++)m[d][a]=0,-1===h[d][a]?f++:f&&(m[d][a]=f,c++);a=0;f=g.length;var k=0;c&&(p="drop");d={};for(var l=0;l<f;d={$jscomp$loop$prop$obj$11$35:d.$jscomp$loop$prop$obj$11$35,$jscomp$loop$prop$shift$36:d.$jscomp$loop$prop$shift$36},l++)d.$jscomp$loop$prop$obj$11$35=g[l],d.$jscomp$loop$prop$shift$36=m[d.$jscomp$loop$prop$obj$11$35.pos.y][d.$jscomp$loop$prop$obj$11$35.pos.x],d.$jscomp$loop$prop$shift$36&&(d.$jscomp$loop$prop$shift$36>a&&(a=d.$jscomp$loop$prop$shift$36),
d.$jscomp$loop$prop$obj$11$35.pos.y+=d.$jscomp$loop$prop$shift$36*b,e.tweens.add({targets:d.$jscomp$loop$prop$obj$11$35,y:d.$jscomp$loop$prop$obj$11$35.y-20*b,duration:80,ease:"Linear",onComplete:function(a){return function(){e.tweens.add({targets:a.$jscomp$loop$prop$obj$11$35,y:a.$jscomp$loop$prop$obj$11$35.y+(80*a.$jscomp$loop$prop$shift$36+20)*b,duration:90*a.$jscomp$loop$prop$shift$36,ease:"Linear",onComplete:function(){k++;k===c&&e.time.delayedCall(100,function(){p="play"})}})}}(d)}));m=null;
H();e.time.delayedCall(90*a,function(){var a=E("horizontal");a=void 0===a?"left":a;m=JSON.parse(JSON.stringify(h));var c=0,b=-1;if("left"===a)for(a=0;9>a;a++){for(var d=!0,f=9;0<=f;f--)m[f][a]=0,-1!=h[f][a]&&(d=!1,c&&(m[f][a]=c));d&&c++}else if("right"===a)for(b=1,a=8;0<=a;a--){d=!0;for(f=9;0<=f;f--)m[f][a]=0,-1!=h[f][a]&&(d=!1,c&&(m[f][a]=c));d&&c++}c=g.length;for(a=0;a<c;a++)if(d=g[a],f=m[d.pos.y][d.pos.x])d.pos.x+=f*b,e.tweens.add({targets:d,x:d.x+80*f*b,duration:90*f,ease:"Linear"});m=null;H();
a:{for(b=0;10>b;b++)for(c=-1,a=0;9>a;a++){if(-1!=h[b][a]&&c===h[b][a]){b=!0;break a}c=h[b][a]}for(b=0;9>b;b++)for(c=-1,a=9;0<=a;a--){if(-1!=h[a][b]&&c===h[a][b]){b=!0;break a}c=h[a][b]}b=void 0}b||(n<z?(p="pre_gameover",e.time.delayedCall(1E3,K)):L());play_sound("drop",e)})}function E(a){if("vertical"===a)return 1===player_data.level?"down":2===player_data.level?"up":3===player_data.level?"down":4===player_data.level?"up":Math.round(Math.random())?"up":"down";if("horizontal"===a)return 1===player_data.level?
"left":2===player_data.level?"right":3===player_data.level?"right":4===player_data.level?"left":Math.round(Math.random())?"left":"right"}function H(){for(var a=0;10>a;a++)for(var c=0;9>c;c++)h[a][c]=-1;a=g.length;for(c=0;c<a;c++){var b=g[c];h[b.pos.y][b.pos.x]=b.frame.name}}function G(){M.setText(n);N.setText(n+"/"+z);n>bestscore&&(bestscore=n,O.setText(bestscore));I.width=n<=z?n/z*322:322}function P(a){play_sound("bounce",e);a.x-=5;e.tweens.add({targets:a,duration:100,x:a.x+10,yoyo:!0,ease:"Linear",
onComplete:function(){a.x+=5}})}function L(){p="pre_completed";e.time.delayedCall(1E3,function(){if(g.length){C=e.add.text(360,640,"BONUS\n+"+A,{fontFamily:"vanilla",fontSize:40,align:"center",color:"#FFFFFF"}).setOrigin(.5);var a=g.length,c=1,b=a;10<a&&(b=10);e.time.addEvent({delay:300,callback:function(){0<A&&(A-=50,C.setText("BONUS\n+"+A));r.setPosition(g[g.length-c].x,g[g.length-c].y);r.explode();g[g.length-c].destroy(!0,!0);play_sound("bonus",e);c++;c===b+1&&e.time.delayedCall(500,function(){C.setText("");
if(10<a){for(var c=0;c<a-b;c++)r.setPosition(g[c].x,g[c].y),r.explode(),g[c].destroy(!0,!0);e.time.delayedCall(500,D)}else D()})},repeat:b-1})}else D()})}function D(){play_sound("completed",e);n>=bestscore&&localStorage.setItem(storage_key,bestscore);p="completed";player_data.level++;n+=A;player_data.score=n;var a=e.add.rectangle(0,0,config.width,config.height,0).setOrigin(0);a.setInteractive();a.alpha=0;e.tweens.add({targets:a,alpha:.5,duration:200});e.add.sprite(360,670,"popup_completed");draw_button(360,
755,"next",e);draw_button(360,870,"menu",e);e.add.text(360,410,"COMPLETED",{fontFamily:"vanilla",fontSize:30,align:"center",color:"#FFFFFF"}).setOrigin(.5);e.add.text(460,549,"+"+F,{fontFamily:"vanilla",fontSize:35,align:"right",color:"#FFFFFF"}).setOrigin(1,.5);e.add.text(360,630,"BONUS +"+A,{fontFamily:"vanilla",fontSize:30,align:"center",color:"#FFFFFF"}).setOrigin(.5)}function K(){play_sound("gameover",e);n>=bestscore&&localStorage.setItem(storage_key,bestscore);p="gameover";var a=e.add.rectangle(0,
0,config.width,config.height,0).setOrigin(0);a.setInteractive();a.alpha=0;e.tweens.add({targets:a,alpha:.5,duration:200});e.add.sprite(360,670,"popup_gameover");draw_button(360,755,"restart",e);draw_button(360,870,"menu",e);e.add.text(360,410,"GAMEOVER",{fontFamily:"vanilla",fontSize:30,align:"center",color:"#FFFFFF"}).setOrigin(.5);e.add.text(360,549,"LEVEL "+player_data.level+" FAILED!",{fontFamily:"vanilla",fontSize:30,align:"center",color:"#FFFFFF"}).setOrigin(.5);e.add.text(360,610,"TOTAL SCORE: "+
n,{fontFamily:"vanilla",fontSize:22,align:"center",color:"#FFFFFF"}).setOrigin(.5)}this.add.sprite(config.width/2,config.height/2,"bg_game");this.add.sprite(360,118,"header");this.add.sprite(360,284,"chain");var e=this,p="play",J=this.add.group(),g=[],n=0;if(1===player_data.level)var z=500;else z=prev_target+500+10*(player_data.level-1),n=player_data.score;prev_target=player_data.score=0;var A=500,F=0,Q=(config.width-720)/2+40,h=Array(10);draw_button(668,49,"pause",this);var q=draw_button(51,49,"sound_on",
this);q.name="sound";check_audio(q);this.add.sprite(144,127,"score_bar");this.add.sprite(573,127,"best_bar");this.add.sprite(360,193,"bg_progress");var I=this.add.tileSprite(199,179,322,28,"progress");I.setOrigin(0);this.add.sprite(184,193,"score_icon");var C;this.add.text(360,60,"Lv."+player_data.level,{fontFamily:"vanilla",fontSize:40,align:"center",color:"#FFFFFF"}).setOrigin(.5);var M=this.add.text(215,127,n,{fontFamily:"vanilla",fontSize:28,align:"right",color:"#FFFFFF"}).setOrigin(1,.5),O=this.add.text(650,
127,bestscore,{fontFamily:"vanilla",fontSize:28,align:"right",color:"#FFFFFF"}).setOrigin(1,.5),N=this.add.text(360,192,0,{fontFamily:"vanilla",fontSize:23,align:"center",color:"#FFFFFF"}).setOrigin(.5);G();this.add.sprite(config.width/2,760,"board");for(q=0;10>q;q++){h[q]=[];for(var u=0;9>u;u++){var t=2+player_data.level;6<t&&(t=6);h[q].push(Math.floor(Math.random()*t))}}for(u=q=0;9>u;u++)for(t=9;0<=t;t--){q++;var B=this.add.sprite(Q+80*u,400+80*t,"jewels");B.setFrame(h[t][u]);B.setInteractive();
B.block=!0;B.uid=q;B.pos={x:u,y:t};g.push(B)}var r=this.add.particles("particle").createEmitter({lifespan:800,quantity:15,scale:{start:1,end:0},speed:{min:70,max:100},frequency:50});r.setPosition(400,300);r.setBlendMode(Phaser.BlendModes.ADD);r.stop();this.input.on("gameobjectdown",function(a,c){"play"===p&&c.block&&!b(c.pos)&&P(c);c.button&&(play_sound("click",this),this.tweens.add({targets:c,scaleX:.9,scaleY:.9,yoyo:!0,ease:"Linear",duration:100,onComplete:function(){if("play"===p){if("pause"===
c.name){p="paused";var a=e.add.rectangle(0,0,config.width,config.height,0).setOrigin(0);a.setInteractive();a.alpha=0;e.tweens.add({targets:a,alpha:.5,duration:200});var b=e.add.sprite(360,670,"popup_pause"),d=e.add.text(360,410,"PAUSED",{fontFamily:"vanilla",fontSize:30,align:"center",color:"#FFFFFF"}).setOrigin(.5),g=draw_button(360,600,"resume",e),h=draw_button(360,720,"restart",e),k=draw_button(360,840,"menu",e),l=draw_button(610,400,"close",e);J.addMultiple([a,b,d,g,h,k,l])}}else if("resume"===
c.name||"close"===c.name)p="play",J.clear(!0,!0);"sound"===c.name?switch_audio(c):"restart"===c.name?(player_data.level=1,e.scene.restart()):"menu"===c.name||"back"===c.name?(player_data.level=1,e.scene.start("menu")):"next"===c.name&&(prev_target=z,e.scene.restart())}},this))},this);this.input.keyboard.on("keydown",function(a){if(" "===a.key){for(var c=0;10>c;c++)for(var b=-1,f=0;9>f;f++)-1!=h[c][f]&&b===h[c][f]&&(console.log(f+", "+c),l(f,c).alpha=.5),b=h[c][f];for(c=0;9>c;c++)for(b=-1,f=9;0<=f;f--)-1!=
h[f][c]&&b===h[f][c]&&(console.log(c+", "+f),l(c,f).alpha=.5),b=h[f][c]}if("q"===a.key)for(a=g.length,c=0;c<a;c++)b=g[c],e.add.text(b.x,b.y,String(h[b.pos.y][b.pos.x]),{fontFamily:"Arial",fontSize:25,align:"center",color:"#00000"})});var m,w=0};function play_sound(b,k){game_settings.sound&&k.sound.play(b)}function switch_audio(b){game_settings[b.name]?(game_settings[b.name]=!1,b.setTexture("btn_sound_off")):(game_settings[b.name]=!0,b.setTexture("btn_sound_on"))}
function check_audio(b){game_settings[b.name]?b.setTexture("btn_sound_on"):b.setTexture("btn_sound_off")}function draw_button(b,k,l,v){b=v.add.sprite(b,k,"btn_"+l).setInteractive();b.button=!0;b.name=l;return b}var config={type:Phaser.AUTO,width:720,height:1280,scale:{mode:Phaser.Scale.FIT,parent:"game_content",autoCenter:Phaser.Scale.CENTER_BOTH},scene:[Boot,Load,Menu,Game]},game=new Phaser.Game(config);
