var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(e){var m=function(){};m.prototype=e;return new m};$jscomp.underscoreProtoCanBeSet=function(){var e={a:!0},m={};try{return m.__proto__=e,m.a}catch(y){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(e,m){e.__proto__=m;if(e.__proto__!==m)throw new TypeError(e+" is not extensible");return e}:null;
$jscomp.inherits=function(e,m){e.prototype=$jscomp.objectCreate(m.prototype);e.prototype.constructor=e;if($jscomp.setPrototypeOf){var y=$jscomp.setPrototypeOf;y(e,m)}else for(y in m)if("prototype"!=y)if(Object.defineProperties){var v=Object.getOwnPropertyDescriptor(m,y);v&&Object.defineProperty(e,y,v)}else e[y]=m[y];e.superClass_=m.prototype};var game_mode="local",game_sound=!0,Boot=function(){return Phaser.Scene.call(this,"boot")||this};$jscomp.inherits(Boot,Phaser.Scene);
Boot.prototype.preload=function(){this.load.image("background","img/background.png");this.load.image("game_title","img/game_title.png");this.load.image("btn_start","img/btn_start.png")};Boot.prototype.create=function(){this.scene.start("load")};var Loader=function(){var e=Phaser.Scene.call(this,"load")||this;e.group;return e};$jscomp.inherits(Loader,Phaser.Scene);
Loader.prototype.preload=function(){this.group=this.add.group();this.add.sprite(360,540,"background");this.add.sprite(360,380,"game_title");var e=this.add.rectangle(360,580,540,28,0);e.alpha=.4;var m=this.add.rectangle(360,580,526,16,16777215);this.group.addMultiple([e,m]);this.load.on("progress",function(e){m.width=526*e});this.load.image("board","img/board.png");this.load.image("shadow_board","img/shadow_board.png");this.load.image("btn_pause","img/btn_pause.png");this.load.image("btn_sound","img/btn_sound.png");
this.load.image("btn_sound_off","img/btn_sound_off.png");this.load.image("btn_multi","img/btn_multi.png");this.load.image("btn_single","img/btn_single.png");this.load.image("btn_about","img/btn_about.png");this.load.image("btn_exit","img/btn_exit.png");this.load.image("btn_close","img/btn_close.png");this.load.image("btn_restart","img/btn_restart.png");this.load.image("btn_resume","img/btn_resume.png");this.load.image("highlight","img/highlight.png");this.load.image("txt_lose","img/txt_lose.png");
this.load.image("txt_player1","img/txt_player1.png");this.load.image("txt_player2","img/txt_player2.png");this.load.image("txt_win","img/txt_win.png");this.load.image("txt_paused","img/txt_paused.png");this.load.image("txt_menu","img/txt_menu.png");this.load.image("txt_about","img/txt_about.png");this.load.image("white","img/white.png");this.load.image("white_king","img/white_king.png");this.load.image("black","img/black.png");this.load.image("black_king","img/black_king.png");this.load.image("window",
"img/window.png");this.load.image("shadow_window","img/shadow_window.png");this.load.image("header","img/header.png");this.load.image("about","img/about.png");this.load.audio("click","audio/click.mp3");this.load.audio("completed","audio/completed.mp3");this.load.audio("gameover","audio/gameover.mp3");this.load.audio("placed1","audio/placed1.mp3");this.load.audio("placed2","audio/placed2.mp3");this.load.audio("swap","audio/swap.mp3")};
Loader.prototype.create=function(){this.group.destroy(!0,!0);var e=this.add.sprite(360,580,"btn_start").setInteractive();this.tweens.add({targets:e,scaleX:.95,scaleY:.95,ease:"Linear",duration:600,yoyo:!0,loop:-1});this.input.on("gameobjectdown",function(){this.scene.start("menu")},this)};var Menu=function(){return Phaser.Scene.call(this,"menu")||this};$jscomp.inherits(Menu,Phaser.Scene);
Menu.prototype.create=function(){var e=this,m="menu",y;this.add.sprite(360,540,"background");this.add.sprite(404,720,"shadow_window");var v=this.add.sprite(360,-144,"game_title").setInteractive();this.add.sprite(360,616,"window");this.add.sprite(360,384,"txt_menu");this.tweens.add({targets:v,y:144,ease:"Back.easeOut",duration:500});v=this.add.sprite(360,544,"btn_single").setInteractive();v.button=!0;v.name="single";v=this.add.sprite(360,656,"btn_multi").setInteractive();v.button=!0;v.name="multi";
v=this.add.sprite(360,768,"btn_about").setInteractive();v.button=!0;v.name="about";this.input.on("gameobjectdown",function(v,F){play_sound("click",e);e.tweens.add({targets:F,scaleX:.9,scaleY:.9,ease:"Linear",duration:100,yoyo:!0,onComplete:function(){if("menu"===m)if("single"===F.name)game_mode="bot",e.scene.start("game");else if("multi"===F.name)game_mode="local",e.scene.start("game");else{if("about"===F.name){m="about";y=e.add.group();var v=e.add.sprite(360,616,"window"),D=e.add.sprite(360,384,
"txt_about"),I=e.add.sprite(360,780,"btn_close").setInteractive();I.button=!0;I.name="close";var q=e.add.sprite(360,600,"about");y.addMultiple([v,D,I,q])}}else"close"===F.name&&(y.destroy(!0,!0),m="menu")}})})};var Game=function(){return Phaser.Scene.call(this,"game")||this};$jscomp.inherits(Game,Phaser.Scene);
Game.prototype.create=function(){function e(){function c(b,a){var g={x:b.x,y:b.y};var c={x:1,y:1};q(c,g)&&2===d[g.y+c.y][g.x+c.x].type&&(c={x:-1,y:-1},q(c,g)&&(d[g.y+c.y][g.x+c.x].filled||k(b.ori,"dump")));c={x:-1,y:1};q(c,g)&&2===d[g.y+c.y][g.x+c.x].type&&(c={x:1,y:-1},q(c,g)&&(d[g.y+c.y][g.x+c.x].filled||k(b.ori,"dump")))}function a(b,c){var a={x:b.x,y:b.y};if(q(c,a))if(d[a.y+c.y][a.x+c.x].filled&&2===d[a.y+c.y][a.x+c.x].type){var g={x:-1,y:-1*c.y};q(g,b.ori)&&d[b.ori.y+g.y][b.ori.x+g.x].filled&&
1===d[b.ori.y+g.y][b.ori.x+g.x].type&&(g={x:-2,y:-2*c.y},q(g,b.ori)&&(d[b.ori.y+g.y][b.ori.x+g.x].filled||k(b.ori,"dump")));g={x:1,y:-1*c.y};q(g,b.ori)&&d[b.ori.y+g.y][b.ori.x+g.x].filled&&1===d[b.ori.y+g.y][b.ori.x+g.x].type&&(g={x:2,y:-2*c.y},q(g,b.ori)&&(d[b.ori.y+g.y][b.ori.x+g.x].filled||k(b.ori,"dump")))}else if(1===d[a.y+c.y][a.x+c.x].type||!d[a.y+c.y][a.x+c.x].filled)if(0<c.x){var f=0;g={x:1,y:-1};q(g,a)&&d[a.y+g.y][a.x+g.x].filled&&f++;g={x:-1,y:1};q(g,a)&&d[a.y+g.y][a.x+g.x].filled&&f++;
2===f&&p(b.ori,"save")}else f=0,g={x:-1,y:-1},q(g,a)&&d[a.y+g.y][a.x+g.x].filled&&f++,g={x:1,y:1},q(g,a)&&d[a.y+g.y][a.x+g.x].filled&&f++,2===f&&p(b.ori,"save")}function k(a,c){var g=1;a:for(;3>g;g++)for(var f=b[g].length,d=0;d<f;d++){var k=b[g][d];if(k.ori.x===a.x&&k.ori.y===a.y){"dump"===c?b[3].push(k):b[0].push(k);b[g].splice(d,d+1);break a}}}function p(a){for(var g=b[2].length,c=0;c<g;c++){var f=b[2][c];if(f.ori.x===a.x&&f.ori.y===a.y){b[1].push(f);b[2].splice(c,c+1);break}}}function l(b,a,c){q(b,
a)&&(d[a.y+b.y][a.x+b.x].filled?d[a.y+b.y][a.x+b.x].type===c&&(b={x:-1*b.x,y:-1*b.y},q(b,a)&&(d[a.y+b.y][a.x+b.x].filled&&d[a.y+b.y][a.x+b.x].type!==c?k({x:a.x+b.x,y:a.y+b.y},"dump"):d[a.y+b.y][a.x+b.x].filled||k({x:a.x+b.x,y:a.y+b.y},"dump"))):(b={x:-1*b.x,y:-1*b.y},q(b,a)&&d[a.y+b.y][a.x+b.x].filled&&d[a.y+b.y][a.x+b.x].type===c&&k(a,"priority")))}function f(a,c,f){if(q(a,c)){var k={x:c.x+a.x,y:c.y+a.y};if(d[k.y][k.x].filled)d[c.y+a.y][c.x+a.x].type===f&&(a={x:2*a.x,y:2*a.y},q(a,c)&&(d[c.y+a.y][c.x+
a.x].filled||b[0].push({x:c.x+a.x,y:c.y+a.y,ori:c,match:!0})));else{for(var p=!0,g,n=0;4>n;n++)if(0===n?g={x:1,y:1}:1===n?g={x:-1,y:1}:2===n?g={x:1,y:-1}:3===n&&(g={x:-1,y:-1}),q(g,k)&&d[k.y+g.y][k.x+g.x].filled&&d[k.y+g.y][k.x+g.x].type===f){var l;if(2<=n){if(l=D({x:k.x+g.x,y:k.y+g.y})){7===k.x&&6===k.y?b[1].push({x:c.x+a.x,y:c.y+a.y,ori:c}):b[3].push({x:c.x+a.x,y:c.y+a.y,ori:c});p=!1;break}}else{(l=D(c))?6===k.x&&7===k.y?b[1].push({x:c.x+a.x,y:c.y+a.y,ori:c}):b[3].push({x:c.x+a.x,y:c.y+a.y,ori:c}):
(6===k.x&&7===k.y?b[1].push({x:c.x+a.x,y:c.y+a.y,ori:c}):b[2].push({x:c.x+a.x,y:c.y+a.y,ori:c}),p=!1);break}}p&&b[1].push({x:c.x+a.x,y:c.y+a.y,ori:c})}}}for(var b=[[],[],[],[]],r=u.getLength(),n=u.getChildren(),z=0;z<r;z++){var e=n[z];if(1===e.type){var h={x:-1,y:1};f(h,e.pos,2);h={x:1,y:1};f(h,e.pos,2);e.king&&(h={x:-1,y:-1},f(h,e.pos,2),h={x:1,y:-1},f(h,e.pos,2))}}if(0===b[0].length)for(z=0;z<r;z++)e=n[z],1===e.type&&(h={x:-1,y:1},l(h,e.pos,2),h={x:1,y:1},l(h,e.pos,2),e.king&&(h={x:-1,y:-1},l(h,
e.pos,2),h={x:1,y:-1},l(h,e.pos,2)));if(0<b[2].length&&0===b[1].length)for(n=b[2].length,r=0;r<n;r++)n=b[2][r],a(n,{x:n.x-n.ori.x,y:n.y-n.ori.y}),n=b[2].length;if(0<b[1].length)for(r=b[1].length,n=0;n<r;n++)z=b[1][n],D(z.ori)&&(c(z,{x:z.x-z.ori.x,y:z.y-z.ori.y}),r=b[1].length);O=b;r=!0;for(n=0;n<b.length;n++)if(0<b[n].length){r=!1;n=b[n][Math.floor(Math.random()*b[n].length)];w=n.ori;n.match&&(d[n.y][n.x].match=!0);G({x:n.x,y:n.y},1);break}r&&L("win")}function m(){B&&(B=!1);h=1===h?2:1;"local"===
game_mode?v():2===h?v():e()}function y(){for(var c=u.getLength(),a=u.getChildren(),k=0;k<c;k++){var d=a[k];if(d.pos.x===w.x&&d.pos.y===w.y){1===d.type?d.setTint(11927519):d.setTint(16711727);d.tinted=!0;break}}}function v(){var c=F();if(0<c.length){P=!0;for(var a=H.getLength(),d=H.getChildren(),p=0;p<c.length;p++)for(var l=0;l<a;l++){var f=d[l];f.pos.x===c[p].x&&f.pos.y===c[p].y&&(f.alpha=1,f.show=!0)}}else P=!1,U()}function U(){function c(b,c,f){q(b,c)&&(d[c.y+b.y][c.x+b.x].filled||(a=!1))}for(var a=
!0,k=u.getLength(),p=u.getChildren(),l=0;l<k;l++){var f=p[l];if(f.type===h){var b=void 0;f=f.pos;var r=void 0;2===h?(b={x:-1,y:-1},r=1):1===h&&(b={x:-1,y:1},r=2);c(b,f,r);2===h?b={x:1,y:-1}:1===h&&(b={x:1,y:1});c(b,f,r);a&&D(f)&&(1===h?(b={x:-1,y:-1},r=1):2===h&&(b={x:-1,y:1},r=2),c(b,f,r),1===h?b={x:1,y:-1}:2===h&&(b={x:1,y:1}),c(b,f,r))}}a&&("bot"===game_mode?2===h&&L("lose"):2===h?L("player2"):L("player1"))}function F(){function c(b,a,c){q(b,a)&&d[a.y+b.y][a.x+b.x].filled&&d[a.y+b.y][a.x+b.x].type===
c&&(b={x:2*b.x,y:2*b.y},q(b,a)&&(d[a.y+b.y][a.x+b.x].filled||p.push({x:a.x+b.x,y:a.y+b.y,ori:a})))}for(var a=u.getLength(),k=u.getChildren(),p=[],l=0;l<a;l++){var f=k[l];if(f.type===h){var b=void 0;f=f.pos;var r=void 0;2===h?(b={x:-1,y:-1},r=1):1===h&&(b={x:-1,y:1},r=2);c(b,f,r);2===h?b={x:1,y:-1}:1===h&&(b={x:1,y:1});c(b,f,r);D(f)&&(1===h?b={x:-1,y:-1}:2===h&&(b={x:-1,y:1}),c(b,f,r),1===h?b={x:1,y:-1}:2===h&&(b={x:1,y:1}),c(b,f,r))}}return p}function K(c){function a(a,b,c){q(a,b)&&d[b.y+a.y][b.x+
a.x].filled&&d[b.y+a.y][b.x+a.x].type===c&&(a={x:2*a.x,y:2*a.y},q(a,b)&&!d[b.y+a.y][b.x+a.x].filled&&(w=b,p={x:b.x+a.x,y:b.y+a.y,ori:b},d[p.y][p.x].match=!0))}var k=D(c),p=!1;if(1===h){var l={x:-1,y:1};a(l,c,2);l={x:1,y:1};a(l,c,2);k&&(l={x:-1,y:-1},a(l,c,2),l={x:1,y:-1},a(l,c,2))}else 2===h&&(l={x:-1,y:-1},a(l,c,1),l={x:1,y:-1},a(l,c,1),k&&(l={x:-1,y:1},a(l,c,1),l={x:1,y:1},a(l,c,1)));return p}function D(c){for(var a=u.getLength(),d=u.getChildren(),p=!1,l=0;l<a;l++){var f=d[l];if(f.pos.x===c.x&&
f.pos.y===c.y){f.king&&(p=!0);break}}return p}function I(c,a){function k(a,b,c){q(a,b)&&(d[b.y+a.y][b.x+a.x].filled?d[b.y+a.y][b.x+a.x].type===c&&(a={x:2*a.x,y:2*a.y},q(a,b)&&!d[b.y+a.y][b.x+a.x].filled&&(p.push({x:b.x+a.x,y:b.y+a.y,match:!0}),l=!0)):p.push({x:b.x+a.x,y:b.y+a.y}))}var p=[],l=!1;Q();var f=D(a);if(2===c){var b={x:-1,y:-1};k(b,a,1);b={x:1,y:-1};k(b,a,1);f&&(b={x:-1,y:1},k(b,a,1),b={x:1,y:1},k(b,a,1))}1===c&&(b={x:-1,y:1},k(b,a,2),b={x:1,y:1},k(b,a,2),f&&(b={x:-1,y:-1},k(b,a,2),b={x:1,
y:-1},k(b,a,2)));f=!0;if(l)for(b=0;b<p.length;b++)p[b].match||(p.splice(b,b+1),b--);else P&&(f=!1);if(f&&0<p.length){S=!0;w=a;y();f=H.getLength();b=H.getChildren();for(var e=0;e<p.length;e++)for(var h=0;h<f;h++){var m=b[h];m.pos.x===p[e].x&&m.pos.y===p[e].y&&(m.alpha=1,m.show=!0,d[m.pos.y][m.pos.x].available=!0,l&&(d[m.pos.y][m.pos.x].match=!0))}}}function q(c,a){var d=!1;0<=a.x+c.x&&8>a.x+c.x&&0<=a.y+c.y&&8>a.y+c.y&&(d=!0);return d}function Q(){if(S){for(var c=H.getLength(),a=H.getChildren(),k=0;k<
c;k++){var e=a[k];e.show&&(e.alpha=0,e.show=!1,d[e.pos.y][e.pos.x].available=!1,d[e.pos.y][e.pos.x].match&&(d[e.pos.y][e.pos.x].match=!1))}c=u.getLength();a=u.getChildren();for(k=0;k<c;k++)e=a[k],e.tinted&&(e.tinted=!1,e.clearTint())}}function M(c,a){play_sound("swap",t);setTimeout(function(){for(var e=u.getLength(),h=u.getChildren(),l=0;l<e;l++){var f=h[l];if(f.pos.x===c&&f.pos.y===a){d[f.pos.y][f.pos.x].filled=!1;d[f.pos.y][f.pos.x].type=0;f.destroy(!0,!0);break}}},150)}function G(c,a){for(var e=
u.getLength(),p=u.getChildren(),l={},f=0;f<e;l={$jscomp$loop$prop$p$28:l.$jscomp$loop$prop$p$28},f++)if(l.$jscomp$loop$prop$p$28=p[f],l.$jscomp$loop$prop$p$28.pos.x===w.x&&l.$jscomp$loop$prop$p$28.pos.y===w.y){d[c.y][c.x].match&&(B=!0,d[c.y][c.x].match=!1,c.y<w.y?c.x>w.x?M(c.x-1,c.y+1):M(c.x+1,c.y+1):c.y>w.y&&(c.x>w.x?M(c.x-1,c.y-1):M(c.x+1,c.y-1)));l.$jscomp$loop$prop$p$28.pos=c;d[w.y][w.x].filled=!1;d[c.y][c.x].filled=!0;d[c.y][c.x].type=d[w.y][w.x].type;d[w.y][w.x].type=0;t.tweens.add({targets:l.$jscomp$loop$prop$p$28,
x:141+63*c.x,y:313+63*c.y,ease:"Sine.easeInOut",duration:300,onComplete:function(a){return function(){1===h?7!==a.$jscomp$loop$prop$p$28.pos.y||a.$jscomp$loop$prop$p$28.king||(a.$jscomp$loop$prop$p$28.king=!0,1===a.$jscomp$loop$prop$p$28.type&&a.$jscomp$loop$prop$p$28.setTexture("white_king")):2!==h||0!==a.$jscomp$loop$prop$p$28.pos.y||a.$jscomp$loop$prop$p$28.king||(a.$jscomp$loop$prop$p$28.king=!0,2===a.$jscomp$loop$prop$p$28.type&&a.$jscomp$loop$prop$p$28.setTexture("black_king"));if("bot"===game_mode)if(2===
h)if(B){B=!1;var b=K(a.$jscomp$loop$prop$p$28.pos);b?G({x:b.x,y:b.y},2):m()}else m();else 1===h&&(B?(B=!1,(b=K(a.$jscomp$loop$prop$p$28.pos))?G({x:b.x,y:b.y},1):m()):m());else"local"===game_mode&&(1===h?B?(B=!1,(b=K(a.$jscomp$loop$prop$p$28.pos))?G({x:b.x,y:b.y},1):m()):m():2===h&&(B?(B=!1,(b=K(a.$jscomp$loop$prop$p$28.pos))?G({x:b.x,y:b.y},2):m()):m()))}}(l)});break}Q()}function L(c){"lose"===c?play_sound("gameover",t):play_sound("completed",t);J="gameover";var a=t.add.rectangle(0,0,720,1080,0).setOrigin(0);
a.alpha=0;t.tweens.add({targets:a,alpha:.5,ease:"Sine.easeOut",duration:500});c=t.add.sprite(360,1280,"txt_"+c);t.tweens.add({targets:c,y:540,ease:"Back.easeOut",duration:600});setTimeout(function(){t.scene.start("menu")},4E3)}var t=this,J="play";this.add.sprite(360,540,"background");this.add.sprite(360,0,"header").setOrigin(.5,0);this.add.sprite(401,671,"shadow_board");this.add.sprite(360,540,"board");var A=this.add.sprite(160,0,"btn_sound").setInteractive();A.setOrigin(.5,0);A.button=!0;A.name=
"sound";game_sound||A.setTexture("btn_sound_off");A=this.add.sprite(576,0,"btn_pause").setInteractive();A.setOrigin(.5,0);A.button=!0;A.name="pause";this.add.group();var H=this.add.group(),u=this.add.group();A=!1;for(var d=[],w,h=2,P=!1,S=!1,B=!1,O,R,C=0;8>C;C++){for(var T=[],E=0;8>E;E++){var x=0;A=A?!1:!0;var N=this.add.sprite(141+63*E,313+63*C,"highlight").setInteractive();N.alpha=0;N.type="table";N.pos={x:E,y:C};H.add(N);3>C?A||(x=this.add.sprite(141+63*E,313+63*C,"white").setInteractive(),x.type=
1,x.piece=!0,x.pos={x:E,y:C},u.add(x),x={filled:!0,type:1}):4<C&&!A&&(x=this.add.sprite(141+63*E,313+63*C,"black").setInteractive(),x.type=2,x.piece=!0,x.pos={x:E,y:C},u.add(x),x={filled:!0,type:2});7===E&&(A=1===C%2?!1:!0);x||(x={filled:!1,type:0});T.push(x)}d.push(T)}this.input.on("gameobjectdown",function(c,a){if("table"===a.type||a.piece&&"play"===J)a.piece?play_sound("placed2",t):play_sound("placed1",t),"local"===game_mode?d[a.pos.y][a.pos.x].available?(G(a.pos,d[a.pos.y][a.pos.x].type),d[a.pos.y][a.pos.x].available=
!1):d[a.pos.y][a.pos.x].filled&&d[a.pos.y][a.pos.x].type===h?I(d[a.pos.y][a.pos.x].type,a.pos):1===h?alert("White turn"):alert("Black turn"):"bot"===game_mode&&(d[a.pos.y][a.pos.x].available?(G(a.pos,d[a.pos.y][a.pos.x].type),d[a.pos.y][a.pos.x].available=!1):d[a.pos.y][a.pos.x].filled&&d[a.pos.y][a.pos.x].type===h?I(d[a.pos.y][a.pos.x].type,a.pos):1===h?alert("White turn"):alert("Black turn"));a.button&&(play_sound("click",t),t.tweens.add({targets:a,scaleX:.9,scaleY:.9,ease:"Linear",duration:100,
yoyo:!0,onComplete:function(){if("play"===J)if("pause"===a.name){J="paused";R=t.add.group();var c=t.add.rectangle(0,0,720,1080,0).setOrigin(0);c.alpha=0;t.tweens.add({targets:c,alpha:.5,ease:"Sine.easeOut",duration:500});var d=t.add.sprite(720,1080,"shadow_window").setOrigin(1),e=t.add.sprite(360,540,"window"),f=t.add.sprite(360,312,"txt_paused"),b=t.add.sprite(360,472,"btn_resume").setInteractive();b.button=!0;b.name="resume";var h=t.add.sprite(360,584,"btn_restart").setInteractive();h.button=!0;
h.name="restart";var n=t.add.sprite(360,696,"btn_exit").setInteractive();n.button=!0;n.name="exit";R.addMultiple([c,d,e,f,b,h,n])}else"sound"===a.name&&(game_sound?(game_sound=!1,a.setTexture("btn_sound_off")):(game_sound=!0,a.setTexture("btn_sound")));else"resume"===a.name?(R.destroy(!0,!0),J="play"):"restart"===a.name?t.scene.start("game"):"exit"===a.name&&t.scene.start("menu")}}))});this.input.keyboard.on("keydown",function(c,a){var d=c.key;if("0"===d||"1"===d||"2"===d||"3"===d){d=Number(d);var e=
u.getLength(),h=u.getChildren();Q();for(var f=0;f<e;f++)for(var b=O[d].length,m=h[f],n=0;n<b;n++){var q=O[d][n];m.pos.x===q.ori.x&&m.pos.y===q.ori.y&&(m.alpha=.5)}}})};function play_sound(e,m){game_sound&&m.sound.play(e)}var config={type:Phaser.AUTO,width:720,height:1080,scale:{mode:Phaser.Scale.FIT,parent:"redfoc",autoCenter:Phaser.Scale.CENTER_BOTH},scene:[Boot,Loader,Menu,Game]},game=new Phaser.Game(config);